objects/Asset_Mac__c.object
<CustomObject>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Asset Mac</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Asset Mac Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Macs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SilverPeakUtilsTest.cls
/*
* Silver Peak Utils Test Class
*/
@isTest
private class SilverPeakUtilsTest
{
    @isTest
    static void testIsPortalUser()
    {
        system.assertEquals(SilverPeakUtils.isPortalUser(), false);
    }

    @isTest
    static void testGetRecordType()
    {
        system.assert(SilverPeakUtils.getRecordTypeId('RMA', 'RMA__c') != null);
    }

    @isTest
    static void testToHex()
    {
        system.assert(SilverPeakUtils.toHex(8) != null);
    }

    @isTest
    static void testGetAssetMac()
    {
        Asset_mac__c amac = new Asset_mac__c(Used__c = false);
        insert amac;
        system.assert(SilverPeakUtils.getAssetMac() != null);
    }

    @isTest
    static void testGetPicklistDefaultValue()
    {
        SilverPeakUtils.getPicklistDefaultValue(Account.Type.getDescribe());
    }
    
    @isTest
    static void testBaseUrl()
    {
        System.assert(SilverPeakutils.getSalesforceBaseUrl() != null);
    }
}