objects/Asset_Mac__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AssetId</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Macs</relationshipLabel>
        <relationshipName>Asset_Macs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Asset Mac</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Asset Mac Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Macs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NewVirtualAssetControllerTest.cls
@isTest
public class NewVirtualAssetControllerTest
{
    @isTest
    static void test()
    {
        Account account = new Account(Name = 'acme');
        insert account;
        Contact contact = new Contact(LastName = 'acme', AccountId = account.Id);
        insert contact;
        Opportunity opportunity = new Opportunity(Name = 'acme', AccountId = account.Id, StageName = 'Discovery', CloseDate = Date.today().addDays(10),Product_Type__c='Both');
        insert opportunity;
        Request__c pocRequest = new Request__c(Opportunity__c = opportunity.Id, POC_Contact__c = contact.Id);
        insert pocRequest;
        Product2 prd = new Product2(Name='acme', Family = 'Virtual Image', IsActive=true);
        insert prd;
        insert new Asset_Mac__c();
        
        PageReference pageRef = new PageReference('/apex/NewVirtualAsset?accountId=' + account.Id + '&requestId=' + pocRequest.Id + '&contactId=' + contact.Id);
        Test.setCurrentPage(pageRef);

        Test.startTest();
        
        Asset asset = new Asset();
        NewVirtualAssetController controller = new NewVirtualAssetController(new ApexPages.StandardController(asset));
        system.assert(controller.Products.size() > 0);
        controller.Asset.Product2Id = controller.Products[0].getValue();
        controller.Asset.Evaluation_End_Date__c = Date.today().addDays(30);
        controller.save();
        
        Test.stopTest();
        
        String assetId = controller.Asset.Id;
        system.assertEquals(true, [select Used__c from Asset_Mac__c where AssetId__c = :assetId limit 1].Used__c);
        system.assertEquals(1, [select count() from License__c where AssetId__c = :assetId]);
        
        controller.Asset = controller.Asset.clone();
        controller.saveAndNew();
    }
}