objects/Asset_Mac__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AssetId</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Macs</relationshipLabel>
        <relationshipName>Asset_Macs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Asset Mac</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Asset Mac Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Macs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_for_Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Sends an email to this contact when new license keys are generated</inlineHelpText>
        <label>Contact for Notification</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Expiration__c</fullName>
        <label>License Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Number of GMS licenses. Always 1 for VX applinaces</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SerialNumber__c</fullName>
        <label>Serial Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>When the license becomes active.</inlineHelpText>
        <label>License Start Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t2CsEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsRecycling__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for email notification triggered by a workflow</description>
        <label>Is Recycling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>CMA</fullName>
        <active>true</active>
        <description>The CMA process is to be executed as a record type on the RMA object</description>
        <label>CMA</label>
    </recordTypes>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2CyEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShipToCompany__c</fullName>
        <label>Ship To Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToCountry__c</fullName>
        <label>Ship To Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Saint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ship_Date__c</fullName>
        <label>Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N500000021gyXEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConvertRmaToCmaController.cls
/*
* Controller for page ConvertRmaToCma
*/
public without sharing class ConvertRmaToCmaController
{
    private String assetId;
    private String virtualProductId;
    private Map<String, String> nxToVxMap;
    private User currentUser;

    public ConvertRmaToCmaController()
    {
        assetId = ApexPages.CurrentPage().getParameters().get('id');
        IsConverted = false;
        currentUser = [select ContactId, Contact.AccountId, Contact.Account.Name from User where Id = :UserInfo.getUserId() and IsActive = true];
        mapCMA();
        buildData();
    }

    public Asset NxAsset { get; set; }
    public String VxModel { get; set; }
    public Boolean IsConverted { get; set; }
    public String CmaId { get; set; }

    public PageReference convert()
    {
        if(createCma())
        {
            PageReference page = new PageReference('/apex/CmaConvertConfirm?id='+CmaId);
            page.setRedirect(true);
            return page;
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Convert Error!'));
            return null;
        }
    }

    private void mapCMA()
    {
        nxToVxMap = new Map<String, String>();
        for(CmaProductMapping__c cma : [select Name, NX__c, VX__c from CmaProductMapping__c])
        {
            nxToVxMap.put(cma.NX__c, cma.VX__c);
        }
    }

    private void buildData()
    {
        NxAsset = [select Id, Model__c, SerialNumber, Ship_Date__c, CreatedDate, ContactId, AccountId, Account.Name, Product2Id,
                        Contract_Number__c, Contract_Type__c, Contract_End__c from Asset where Id = :assetId];
        if(NxAsset != null && String.IsNotEmpty(NxAsset.Model__c))
        {
            VxModel = nxToVXMap.get(NxAsset.Model__c);
            List<Product2> products = [select Id from Product2 where Name = :VxModel];
            if(products.size() > 0)
            {
                virtualProductId = products[0].Id;
            }
        }
    }

    private Boolean createCma()
    {
        Boolean result = false;
        SavePoint sp = Database.setSavePoint();
        try
        {
            // Opens an RMA of CMA record type
            String cmaRecordTypeId = SilverPeakUtils.getRecordTypeId('CMA', 'RMA__c');
            String accountId = getAccountId(NxAsset);
            RMA__c cma = new RMA__c(RecordTypeId = cmaRecordTypeId, Account__c = accountId, Contact__c = currentUser.ContactId, Status__c = 'Initiated', Type__c = 'Convert to Virtual');
            insert cma;
            CmaId = cma.Id;

            List<RMA_Item__c> rmaItems = new List<RMA_Item__c>();
            String rmaItemRecordTypeId = SilverPeakUtils.getRecordTypeId('RMA Return', 'RMA_Item__c');
            String accountName = currentUser.Contact.AccountId != null ? currentUser.Contact.Account.Name : NxAsset.Account.Name;
            //Puts the NX on CMA
            RMA_Item__c rmaItem = new RMA_Item__c(RMA__c = cma.Id, RecordTypeId = rmaItemRecordTypeId, Asset__c = NxAsset.Id, Product2__c = NxAsset.Product2Id, Status__c = 'Pending Return -Conversion',
                                                    Type__c = 'Convert to Virtual', ShipToCompany__c = accountName, Ship_To_Contact__c = currentUser.ContactId);
            rmaItems.add(rmaItem);

            // Executes the creation of the VX with perpetual license
            Asset vxAsset = createVirtualAsset(NxAsset);

            // Adds the new VX to the CMA record as well
            RMA_Item__c cmaItem = new RMA_Item__c(RMA__c = cma.Id, RecordTypeId = rmaItemRecordTypeId, Asset__c = vxAsset.Id, Product2__c = virtualProductId, Status__c = 'Shipped',
                                                    Type__c = 'Convert to Virtual', ShipToCompany__c = accountName, Ship_To_Contact__c = currentUser.ContactId);
            rmaItems.add(cmaItem);
            insert rmaItems;

            Asset createdVxAsset = [select SerialNumber, Contract_Type__c, Contract_End__c, Model__c from Asset where Id = :vxAsset.Id];
            update new Asset(Id = NxAsset.Id, Contract_Number__c = null); //sends email CmaRequestProcessedResult
            System.debug('createdVxAsset: ' + createdVxAsset.Model__c);
            if(isRecycling(NxAsset))
            {
                update new RMA__c(Id = cma.Id, IsRecycling__c = true); // sends email NXApplianceRecyclingInstructions
            }
          
            result = true;
        }
        catch(Exception ex)
        {
            Database.rollback(sp);
            Apexpages.addMessages(ex);
            result = false;
        }
        return result;
    }

    private Asset createVirtualAsset(Asset asset)
    {
        Asset vxAsset = new Asset();
        vxAsset.Evaluation_Start_Date__c = Date.today();
        try
        {
            Asset_mac__c assetMac = SilverPeakUtils.getAssetMac();
            assetMac.Used__c = true;
            upsert assetMac;

            String mac = [select Name from Asset_Mac__c where Id = :assetMac.Id limit 1].Name;
            vxAsset.Name = '001BBC' + SilverPeakUtils.toHex(Integer.valueof(mac));
            vxAsset.SerialNumber = vxAsset.Name;
            vxAsset.Status = 'Customer Owned';
            vxAsset.Quantity = 1;
            vxAsset.Ship_Date__c = Date.today();
            vxAsset.ContactId = currentUser.ContactId;
            String accountId = getAccountId(asset);
            vxAsset.AccountId = accountId;
            vxAsset.Contract_Number__c = asset.Contract_Number__c;
            vxAsset.product2Id = virtualProductId;
            vxAsset.TriggerAutoFulfillEmail__c=true;
            insert vxAsset;

            assetMac.AssetId__c = vxAsset.Id;
            update assetMac;
            createLicense(vxAsset);
            return vxAsset;
        }
        catch(DmlException ex)
        {
            Apexpages.addMessages(ex);
            return null;
        }
    }

    private void createLicense(Asset asset)
    {
        License__c license = new License__c();
        license.Quantity__c = 1;
        license.AssetId__c = asset.Id;
        license.Contact_for_Notification__c = asset.ContactId;
        license.Start_Date__c = asset.Evaluation_Start_Date__c;
        String licenseAsModel = '';
        if(String.isNotEmpty(virtualProductId))
        {
            List<Product2> products = [select LicenseAsModel__c, Model__c from Product2 where Id = :virtualProductId limit 1];
            if(products.size() > 0)
            {
                licenseAsModel = String.isEmpty(products[0].LicenseAsModel__c) ? products[0].Model__c : products[0].LicenseAsModel__c;
            }
        }
        license.Model__c = licenseAsModel;
        license.SerialNumber__c = asset.Name;
        license.License_Expiration__c = null;
        insert license;
        VirtualAssetManager.encryptLicenses(new List<String> { license.Id });
    }

    // NX Recycle Criteria
    private Boolean isRecycling(Asset asset)
    {
        Boolean result = false;
        Set<String> nxRecyleCountries = new Set<String>{ 'China', 'India', 'Russia', 'Brasil'};
        List<RMA_Item__c> rmaItem = [select ShipToCountry__c from RMA_Item__c where Asset__c = :asset.Id];
        if(asset.Ship_Date__c != null && rmaItem.size() > 0)
        {
            if((asset.CreatedDate.addYears(3) > Date.today()) || asset.Model__c == 'NX-1700' || nxRecyleCountries.contains(rmaItem[0].ShipToCountry__c))
            {
                result = true;
            }
        }
        return result;
    }

    private String getAccountId(Asset asset)
    {
        return currentUser.Contact.AccountId == null ? asset.AccountId : currentUser.Contact.AccountId;
    }
}