objects/Builds__c.object
<CustomObject>
    <description>SW Builds related to a release</description>
    <fields>
        <fullName>Build_Details__c</fullName>
        <label>Build Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Build_Number__c</fullName>
        <inlineHelpText>format x.x.y.z_#####</inlineHelpText>
        <label>Build Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECO_Date__c</fullName>
        <inlineHelpText>input date of ECO</inlineHelpText>
        <label>ECO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISO_Model__c</fullName>
        <label>ISO Model</label>
        <picklist>
            <picklistValues>
                <fullName>All VX/VRX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GX-V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to remove visibility in the Support Center Portal</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRecommended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Silver Peak Recommended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReleaseCode__c</fullName>
        <formula>if ( OR( ISPICKVAL(Release__r.Type__c , &apos;GMS&apos;), ISPICKVAL(Release__r.Type__c , &apos;GX-V Image&apos;)),  Build_Number__c  ,
LEFT( Build_Number__c ,(FIND(    &apos;_&apos;, Build_Number__c   , 1)-1)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Release #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>Releases__c</referenceTo>
        <relationshipLabel>Builds</relationshipLabel>
        <relationshipName>Builds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BETA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Build</label>
    <nameField>
        <label>Build Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Releases__c.object
<CustomObject>
    <description>Wrapper for SW Releases</description>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Release_Details__c</fullName>
        <label>Release Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <inlineHelpText>format x.y</inlineHelpText>
        <label>Release Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>VXOA Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GX-V Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO Image</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NewReleaseController.cls
public class NewReleaseController {
    
    public string ReleaseType {get;set;}
    public string ReleaseName {get;set;}
    public string ReleaseId {get;set;}
    public string IsoModelName {get;set;}
    public List<Builds__c> GAOtherBuilds {
        get
        {
            
            return LoadOtherBuilds('GA');
        }
        
    }
    public List<Builds__c> GARecommendedBuilds {
        get
        {
            
            return LoadRecommendedBuilds('GA');
        }
    }
    public List<Builds__c> FCSOtherBuilds {
        get
        {
            
            return LoadOtherBuilds('FCS');
        }
    }
    public List<Builds__c> FCSRecommendedBuilds {
        get
        {
            
            return LoadRecommendedBuilds('FCS');
        }
    }
    public List<Builds__c> PatchOtherBuilds {
        get
        {
            
            return LoadOtherBuilds('PATCH');
        }
    }
    public List<Builds__c> PatchRecommendedBuilds {
        get
        {
            
            return LoadRecommendedBuilds('PATCH');
        }}
    public List<Builds__c> BetaOtherBuilds {
        get
        {
            
            return LoadOtherBuilds('BETA');
        }
    }
    public List<Builds__c> BetaRecommendedBuilds {
        get
        {
            
            return LoadRecommendedBuilds('BETA');
        }
    }
    
    
    public NewReleaseController()
    {
        // Set VapType and ReleaseName
        // 
        ReleaseType=ApexPages.currentPage().getParameters().get('relType');
        ReleaseName=ApexPages.currentPage().getParameters().get('relName');
        ReleaseId=ApexPages.currentPage().getParameters().get('reldtl');
        IsoModelName=ApexPages.currentPage().getParameters().get('model');
        
        
        
    }
    
    private List<Builds__c> LoadRecommendedBuilds(string status)
    {
        if(ReleaseType == 'VMware')
        {
            return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                    from Builds__c where Release__c=:ReleaseId and Status__c=:status and Inactive__c=false and IsRecommended__c=true and Id  in (Select Build_Images__c from Ensemblestorage__EnsembleFile__c)  order by ECO_Date__c desc];
        }
        else  if(ReleaseType == 'VXOA Release' || ReleaseType == 'GMS'||ReleaseType == 'EdgeConnect' )
        {
            return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                    from Builds__c where Release__r.Type__c=:ReleaseType and Status__c=:status and Inactive__c=false and IsRecommended__c=true and Id  in (Select Build_Images__c from Ensemblestorage__EnsembleFile__c) order by ECO_Date__c desc];
        }
        else  
        {
            string tagReleaseName='SW '+ReleaseType;
            return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                    from Builds__c where Release__r.Type__c='ISO Image' and ISO_Model__c=:ReleaseName and Status__c=:status and Inactive__c=false and IsRecommended__c=true and Id  in (Select Build_Images__c from Ensemblestorage__EnsembleFile__c where Ensemblestorage__Tag__c includes(:tagReleaseName)) order by ECO_Date__c desc];
        }
        
    }
    
    
    
    private List<Builds__c> LoadOtherBuilds(string status)
    {
        
        if(ReleaseType == 'VMware')
        {
            return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                    from Builds__c where Release__c=:ReleaseId and Status__c=:status and Inactive__c=false and IsRecommended__c=false and Id  in (Select Build_Images__c from Ensemblestorage__EnsembleFile__c) order by ECO_Date__c desc];
        }
        else  if(ReleaseType == 'VXOA Release' || ReleaseType == 'GMS'|| ReleaseType == 'EdgeConnect' )
        {
            return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                    from Builds__c where Release__r.Type__c=:ReleaseType  and Status__c=:status and Inactive__c=false and IsRecommended__c=false and Id  in (Select Build_Images__c from Ensemblestorage__EnsembleFile__c) order by ECO_Date__c desc];
        }
        else 
        {
            string tagReleaseName='SW '+ReleaseType;
            return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                    from Builds__c where Release__r.Type__c='ISO Image' and ISO_Model__c=:ReleaseName and Status__c=:status and Inactive__c=false and IsRecommended__c=false and Id  in (Select Build_Images__c from Ensemblestorage__EnsembleFile__c where Ensemblestorage__Tag__c includes(:tagReleaseName))   order by ECO_Date__c desc];
        }
        
    }
}