objects/Builds__c.object
<CustomObject>
    <description>SW Builds related to a release</description>
    <fields>
        <fullName>Build_Details__c</fullName>
        <label>Build Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Build_Number__c</fullName>
        <inlineHelpText>format x.x.y.z_#####</inlineHelpText>
        <label>Build Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECO_Date__c</fullName>
        <inlineHelpText>input date of ECO</inlineHelpText>
        <label>ECO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISO_Model__c</fullName>
        <label>ISO Model</label>
        <picklist>
            <picklistValues>
                <fullName>All VX/VRX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GX-V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to remove visibility in the Support Center Portal</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRecommended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Silver Peak Recommended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReleaseCode__c</fullName>
        <formula>if ( OR( ISPICKVAL(Release__r.Type__c , &apos;GMS&apos;), ISPICKVAL(Release__r.Type__c , &apos;GX-V Image&apos;)),  Build_Number__c  ,
LEFT( Build_Number__c ,(FIND(    &apos;_&apos;, Build_Number__c   , 1)-1)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Release #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>Releases__c</referenceTo>
        <relationshipLabel>Builds</relationshipLabel>
        <relationshipName>Builds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BETA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Build</label>
    <nameField>
        <label>Build Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Releases__c.object
<CustomObject>
    <description>Wrapper for SW Releases</description>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Release_Details__c</fullName>
        <label>Release Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <inlineHelpText>format x.y</inlineHelpText>
        <label>Release Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>VXOA Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GX-V Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO Image</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ReleasesController.cls
/**
 * Controller of Releases page.
 */
public with sharing class ReleasesController 
{
    public ReleasesController()
    {
        //ActiveTab = 'VAP';
    }
    
    public List<Releases__c> VapReleases
    {
        get
        {
            return [select Id, Name from Releases__c where Type__c = 'VX Image' or Type__c = 'GX-V Image' order by Name desc];
        }
    }
    
    public List<String> BuildStatuses
    {
        get
        {
            List<String> result = new List<String>();
            for(PickListEntry entry : Builds__c.Status__c.getDescribe().getPicklistValues())
            {
                result.add(entry.getValue());
            }
            return result;
        }
    }
    
    public List<String> ISOModels
    {
        get
        {
            List<String> result = new List<String>();
            for(PickListEntry entry : Builds__c.ISO_Model__c.getDescribe().getPicklistValues())
            {
                result.add(entry.getValue());
            }
            return result;
        }
    }
    
    public List<Builds__c> RecommendedBuilds
    {
        get
        {
            if(ActiveTab == 'VAP')
            {
                if(VAPType == 'VMware')
                {
                    return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                            from Builds__c where Release__c=:ActiveModelTab and Status__c=:ActiveSubTab and Inactive__c=false and IsRecommended__c=true order by ECO_Date__c desc];
                }
                else if(VAPType == 'other')
                {
                    return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                            from Builds__c where Release__r.Type__c='ISO Image' and ISO_Model__c=:ActiveModelTab and Status__c=:ActiveSubTab and Inactive__c=false and IsRecommended__c=true order by ECO_Date__c desc];
                }
                else
                {
                    return null;
                }
            }
            else if(ActiveTab == 'VXOA Release' || ActiveTab == 'GMS' || ActiveTab == 'EdgeConnect')
            {
                
                return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                        from Builds__c where Release__r.Type__c=:ActiveTab and Status__c=:ActiveSubTab and Inactive__c=false and IsRecommended__c=true order by ECO_Date__c desc];
            }
            else
            {
                return null;
            }
        }
    }
    
    public List<Builds__c> OtherBuilds
    {
        get
        {
            if(ActiveTab == 'VAP')
            {
                if(VAPType == 'VMware')
                {
                    return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                            from Builds__c where Release__c=:ActiveModelTab and Status__c=:ActiveSubTab and Inactive__c=false and IsRecommended__c=false order by ECO_Date__c desc];
                }
                else if(VAPType == 'other')
                {
                    return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                            from Builds__c where Release__r.Type__c='ISO Image' and ISO_Model__c=:ActiveModelTab and Status__c=:ActiveSubTab and Inactive__c=false and IsRecommended__c=false order by ECO_Date__c desc];
                }
                else
                {
                    return null;
                }
            }
            else if(ActiveTab == 'VXOA Release' || ActiveTab == 'GMS' || ActiveTab == 'EdgeConnect')
            {
                return [select Id, Name, Build_Details__c, Build_Number__c, Release__r.Release_Details__c, ReleaseCode__c, ECO_Date__c, IsRecommended__c, Release__r.Release_Date__c 
                        from Builds__c where Release__r.Type__c=:ActiveTab and Status__c=:ActiveSubTab and Inactive__c=false and IsRecommended__c=false order by ECO_Date__c desc];
            }
            else
            {
                return null;
            }
        }
    }
    
    public String ActiveTab { get; private set; }    //VAP, VXOA Release or GMS
    public String ActiveSubTab { get; private set; } //GA, FCS, PATCH or BETA
    public String ActiveModelTab { get; private set; } //release id (only for VAP)
    public String VAPType { get; private set; } //VMware, other
    public Boolean RenderVAP { get; private set; }
    
    public PageReference changeBuilds()
    {
        String clickingTab = ApexPages.currentPage().getParameters().get('tab');
        String clickingSubtab = ApexPages.currentPage().getParameters().get('subtab');
        String clickingModel = ApexPages.currentPage().getParameters().get('model');
        String clearPara = ApexPages.currentPage().getParameters().get('clear');
        String clickingVapType = ApexPages.currentPage().getParameters().get('vaptype');
        
        if(String.isNotEmpty(clickingTab))
        {
            ActiveTab = clickingTab;
            if(String.isNotEmpty(clearPara))
            {
                ActiveSubTab = null;
                ActiveModelTab = null;
                VAPType = null;
            }
        }
        if(String.isNotEmpty(clickingSubtab))
        {
            ActiveSubTab = clickingSubtab;
        }
        if(String.isNotEmpty(clickingModel))
        {
            ActiveModelTab = clickingModel;
        }
        if(String.isNotEmpty(clickingVapType))
        {
            VAPType = clickingVapType;
        }
        RenderVAP = ActiveTab == 'VAP' && String.isEmpty(VAPType);
        
        if(String.isEmpty(ActiveSubTab))
        {
            if(ActiveTab == 'VAP')
            {
                if(VAPType == 'VMware')
                {
                        if(VapReleases.size() > 0)
                        {
                            ActiveModelTab = VapReleases[0].Id;
                            ActiveSubTab = BuildStatuses[0];
                        }
                }
                else if(VAPType == 'other')
                {
                        if(ISOModels.size() > 0)
                        {
                            ActiveModelTab = ISOModels[0];
                            ActiveSubTab = BuildStatuses[0];
                        }
                }
            }
            else
            {
                    if(BuildStatuses.size() > 0)
                    {
                        ActiveSubTab = BuildStatuses[0];
                    }
            }
        }
        if(String.isEmpty(ActiveModelTab))
        {
            if(ActiveTab == 'VAP')
            {
                if(VAPType == 'VMware')
                {
                    if(VapReleases.size() > 0)
                    {
                        ActiveModelTab = VapReleases[0].Id;
                    }
                }
                else if(VAPType == 'other')
                {
                    if(ISOModels.size() > 0)
                    {
                        ActiveModelTab = ISOModels[0];
                    }
                }
            }
        }
        return null;
    }
    
    @isTest
    static void testReleasesController()
    {
        ReleasesController controller = new ReleasesController();
        System.assertNotEquals(null, controller.VapReleases);
        System.assertNotEquals(null, controller.BuildStatuses);
        System.assertNotEquals(null, controller.ISOModels);
        
        PageReference page = new PageReference('/apex/releases?tab=VAP&vaptype=VMware');
        Test.setCurrentPage(page);
        controller.changeBuilds();
        System.assertEquals('VAP', controller.ActiveTab);
        System.assertEquals(controller.VapReleases[0].Id, controller.ActiveModelTab);
        List<Builds__c> builds = controller.RecommendedBuilds;
        List<Builds__c> builds2 = controller.OtherBuilds;
        
        page = new PageReference('/apex/releases?tab=VAP&vaptype=other');
        Test.setCurrentPage(page);
        controller.changeBuilds();
        System.assertEquals('VAP', controller.ActiveTab);
        //System.assertEquals(controller.ISOModels[0], controller.ActiveModelTab);
        builds = controller.RecommendedBuilds;
        builds2 = controller.OtherBuilds;
        
        page = new PageReference('/apex/releases?tab=GMS');
        Test.setCurrentPage(page);
        controller.changeBuilds();
        System.assertEquals('GMS', controller.ActiveTab);
        System.assertEquals(controller.BuildStatuses[0], controller.ActiveSubtab);
        builds = controller.RecommendedBuilds;
        builds2 = controller.OtherBuilds;
        
        page = new PageReference('/apex/releases?tab=EdgeConnect');
        Test.setCurrentPage(page);
        controller.changeBuilds();
        System.assertEquals('EdgeConnect', controller.ActiveTab);
        System.assertEquals(controller.BuildStatuses[0], controller.ActiveSubtab);
        builds = controller.RecommendedBuilds;
        builds2 = controller.OtherBuilds;
    }
}