objects/Builds__c.object
<CustomObject>
    <description>SW Builds related to a release</description>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>Releases__c</referenceTo>
        <relationshipLabel>Builds</relationshipLabel>
        <relationshipName>Builds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BETA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Build</label>
    <nameField>
        <label>Build Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Releases__c.object
<CustomObject>
    <description>Wrapper for SW Releases</description>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <inlineHelpText>format x.y</inlineHelpText>
        <label>Release Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>VXOA Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GX-V Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO Image</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestBuildExtension.cls
@IsTest
public class TestBuildExtension {
    
  	@IsTest
    public static void TestBuildExtension_RetreiveFiles()
    {
        Releases__c rel= new  Releases__c();
        rel.Name='TestData';
        rel.Type__c='VX Image';
        rel.Release_Date__c= Date.today();
         rel.Release__c= 'Test Data';
        insert rel;
        
        Builds__c build= new Builds__c();
        build.Name ='Test';
        build.Status__c='GA';
        build.Release__c= rel.Id;
        insert build;
        
        
        PageReference pageRef = new PageReference('/apex/NewBuildDetail?id='+ build.Id+'&relName=VMware');
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController= new ApexPages.StandardController(build);
        BuildExtension bldExtension = new BuildExtension(stdController);
     
        
        
    }
@IsTest
    public static void TestBuildExtension_RetreiveFiles_ISO()
    {
        Releases__c rel= new  Releases__c();
        rel.Name='TestData';
        rel.Type__c='ISO Image';
        rel.Release_Date__c= Date.today();
         rel.Release__c= 'Test Data';
        insert rel;
        
        Builds__c build= new Builds__c();
        build.Name ='Test';
        build.Status__c='GA';
        build.Release__c= rel.Id;
        insert build;
        
        
        PageReference pageRef = new PageReference('/apex/NewBuildDetail?id='+ build.Id+'&relName=TestData');
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController= new ApexPages.StandardController(build);
        BuildExtension bldExtension = new BuildExtension(stdController);
     
        
        
    }
}