objects/Builds__c.object
<CustomObject>
    <description>SW Builds related to a release</description>
    <label>Build</label>
    <nameField>
        <label>Build Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Releases__c.object
<CustomObject>
    <description>Wrapper for SW Releases</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>VXOA Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GX-V Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO Image</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestNewReleasesController.cls
@IsTest
public class TestNewReleasesController {

    @IsTest(SeeAllData=true)
    public static void TestNewReleasesDataVmWare()
    {   
       
        List<Releases__c> vx9000Dtl=[select Id, Name from Releases__c where Type__c = 'VX Image' and Name='VX-9000'];
        PageReference pageRef = new PageReference('/apex/NewReleases?relType=VMware&relName=VX-9000&reldtl='+vx9000Dtl[0].Id);
        Test.setCurrentPage(pageRef);
        NewReleaseController controller = new NewReleaseController();
        System.assertEquals('VX-9000', controller.ReleaseName);
         System.assertEquals('VMware', controller.ReleaseType);
         System.assertEquals(vx9000Dtl[0].Id, controller.ReleaseId);
        List<Builds__c> builds1 = controller.GARecommendedBuilds;
        List<Builds__c> builds2 = controller.GAOtherBuilds;
         List<Builds__c> builds3 = controller.FCSRecommendedBuilds;
        List<Builds__c> builds4 = controller.FCSOtherBuilds;
          List<Builds__c> builds5 = controller.BETARecommendedBuilds;
        List<Builds__c> builds6 = controller.BetaOtherBuilds;
          List<Builds__c> builds7 = controller.PatchRecommendedBuilds;
        List<Builds__c> builds8 = controller.PatchOtherBuilds;
    }
    
    @IsTest(SeeAllData=true)
    public static void TestNewReleasesDataISO()
    {   
       
        List<Releases__c> vx9000Dtl=[select Id, Name from Releases__c where Type__c = 'VX Image' and Name='VX-9000'];
        PageReference pageRef = new PageReference('/apex/NewReleases?relType=Xen&relName=All VX/VRX&model=All VX/VRX');
        Test.setCurrentPage(pageRef);
        NewReleaseController controller = new NewReleaseController();
        System.assertEquals('All VX/VRX', controller.ReleaseName);
         System.assertEquals('Xen', controller.ReleaseType);
         System.assertEquals(null, controller.ReleaseId);
        System.assertEquals('All VX/VRX', controller.IsoModelName);
        
        List<Builds__c> builds1 = controller.GARecommendedBuilds;
        List<Builds__c> builds2 = controller.GAOtherBuilds;
         List<Builds__c> builds3 = controller.FCSRecommendedBuilds;
        List<Builds__c> builds4 = controller.FCSOtherBuilds;
          List<Builds__c> builds5 = controller.BETARecommendedBuilds;
        List<Builds__c> builds6 = controller.BetaOtherBuilds;
          List<Builds__c> builds7 = controller.PatchRecommendedBuilds;
        List<Builds__c> builds8 = controller.PatchOtherBuilds;
    }
    
    @IsTest(SeeAllData=true)
    public static void TestNewReleasesDataVXOImage()
    {   
       
        
        PageReference pageRef = new PageReference('/apex/NewReleases?relType=VXOA Release&model=All VX/VRX&relName=All VX/VRX');
        Test.setCurrentPage(pageRef);
        NewReleaseController controller = new NewReleaseController();
        System.assertEquals('All VX/VRX', controller.ReleaseName);
         System.assertEquals('VXOA Release', controller.ReleaseType);
         System.assertEquals(null, controller.ReleaseId);
        System.assertEquals('All VX/VRX', controller.IsoModelName);
        
        List<Builds__c> builds1 = controller.GARecommendedBuilds;
        List<Builds__c> builds2 = controller.GAOtherBuilds;
         List<Builds__c> builds3 = controller.FCSRecommendedBuilds;
        List<Builds__c> builds4 = controller.FCSOtherBuilds;
          List<Builds__c> builds5 = controller.BETARecommendedBuilds;
        List<Builds__c> builds6 = controller.BetaOtherBuilds;
          List<Builds__c> builds7 = controller.PatchRecommendedBuilds;
        List<Builds__c> builds8 = controller.PatchOtherBuilds;
    }
}