objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_for_Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Sends an email to this contact when new license keys are generated</inlineHelpText>
        <label>Contact for Notification</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>License Key for Virtual Appliances or GMS</description>
        <inlineHelpText>Don&apos;t edit this field, or the key may not work!</inlineHelpText>
        <label>Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiration__c</fullName>
        <label>License Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Number of GMS licenses. Always 1 for VX applinaces</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RenewalKeyGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal Key Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SerialNumber__c</fullName>
        <label>Serial Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>When the license becomes active.</inlineHelpText>
        <label>License Start Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RenewalLicenseController.cls
/*
 *  The controller of Renewal License page.
 */
 public class RenewalLicenseController
 {
    private Asset asset;
    
    public RenewalLicenseController(ApexPages.StandardController controller) 
    {
        asset = (Asset)controller.getRecord();
        License = new License__c();
        License.Start_Date__c = Date.today();
        List<License__c> existingLicenses = [select Id, License_Expiration__c from License__c where AssetId__c=:asset.Id order by License_Expiration__c desc nulls last limit 1];
        if(existingLicenses.size() > 0)
        {
            LastEndDate = (existingLicenses[0].License_Expiration__c == null) ? Date.today() : existingLicenses[0].License_Expiration__c;
        }
        else
        {
            LastEndDate = Date.today();
        }
        LicenseIdJSON = 'null';
    }
    
    public Boolean InProgress { get; set; }
    public String LicenseIdJSON { get; set; }
    public License__c License { get; set; }
    public Date LastEndDate { get; set; }
    
    public PageReference renewLicense()
    {
        License.AssetId__c = asset.Id;
        License.Contact_for_Notification__c = asset.ContactId;
        if(asset.Product2.Product_Category__c != 'GMS')
        {
            License.Quantity__c = 1;
        }
        License.RenewalKeyGenerated__c = true;
        
        Integer numberOfLicenses = (asset.Product2.NumberOfLicenses__c == null) ? 1 : asset.Product2.NumberOfLicenses__c.intValue();
        List<License__c> concretLicenses = new List<License__c>();
        List<License__c> existingLicenses = [select Id, Model__c, SerialNumber__c from License__c where AssetId__c=:asset.Id order by CreatedDate desc limit :numberOfLicenses];
        for(License__c existingLicense : existingLicenses)
        {
            License__c newLicense = License.clone(false, false, false, false);
            newLicense.Model__c = existingLicense.Model__c;
            newLicense.SerialNumber__c = existingLicense.SerialNumber__c;
            concretLicenses.add(newLicense);
        }
        
        try
        {
            insert concretLicenses;
            List<Id> licenseIds = new List<Id>();
            for(License__c license : concretLicenses)
            {
                licenseIds.add(license.Id);
            }
            VirtualAssetManager.encryptLicenses(licenseIds);
            InProgress = true;
            LicenseIdJSON = JSON.serialize(licenseIds);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'License is being generated...'));
        }
        catch(DmlException ex) 
        {
            ApexPages.addMessages(ex);
        }
        return null;
    }
    
    @remoteAction
    public static Boolean hasLicenseGenerated(List<String> licenseId)
    {
        Integer pendingLicenses = [select count() from License__c where Id in :licenseId and Key__c = null];
        return pendingLicenses == 0;
    }
}