objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>IsAllVirtual__c</fullName>
        <formula>IF( 

OR( 
LEFT(TEXT( Evaluation_Product_1__c ) ,1) = &apos;N&apos;,
LEFT(TEXT( Evaluation_Product_2__c ) ,1) = &apos;N&apos;, 
CONTAINS(TEXT( Evaluation_Product_1__c ) ,&apos;GX-1000&apos;), 
CONTAINS(TEXT( Evaluation_Product_2__c ) ,&apos;GX-1000&apos;),
NOT(ISBLANK(TEXT( PhysicalProduct1__c )))

), 0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsAllVirtual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VirtualProduct1__c</fullName>
        <label>Virtual Product1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unity Cloud Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AutomateVirtualPOCBatch.cls
public class AutomateVirtualPOCBatch implements Schedulable, Database.Batchable<sObject>, Database.Stateful
{
    Set<string>	successPOCIds;
    Set<string> errorPOCIds;
    Set<string> unityPocsIds;
    public void execute(SchedulableContext context)
    {
        Database.executeBatch(new AutomateVirtualPOCBatch(), 10);
    }
    
    public Database.QueryLocator start(Database.BatchableContext context)
    {
        List<Date> lstDates= new List<Date>();
        lstDates.add(Date.today());
        lstDates.add(Date.today().addDays(-1));
        return Database.getQueryLocator([Select Id,Name,POC_Contact__c from Request__c where Requested_Delivery_Date__c in:lstDates and  POC_Type__c='WAN Op' and Status__c='Approved to Ship' and IsAllVirtual__c=1 and VirtualProduct1__c != null]);
    }
    
    public void execute(Database.BatchableContext context, List<sObject> scope)
    {
        successPOCIds = new Set<string>();
        errorPOCIds = new Set<string>();
        unityPocsIds= new Set<string>();
        List<Id> licenseIds= new List<Id>();
        Boolean isCustomerUser=false;
        Boolean isPartnerUser =false;
        if(scope.size()>0)
        {
            for(sObject item :scope)
            {
                
                Request__c pocRequest= (Request__c)item;
                System.Savepoint sp= Database.setSavepoint();
                try
                {
                    isCustomerUser = AutomatePOCShipmentHelper.ValidateCustomerPortalLogic(pocRequest.POC_Contact__c);
                    
                    if(!isCustomerUser)
                    {
                        isPartnerUser = AutomatePOCShipmentHelper.ValidatePartnerPortalLogic(pocRequest.POC_Contact__c);
                        
                    }
                    if( isCustomerUser || isPartnerUser)
                    {
                        successPOCIds.add(string.valueof(pocRequest.Name));
                        licenseIds.addAll(AutomatePOCShipmentHelper.FulfillPocs(pocRequest.Id));
                        if(AutomatePOCShipmentHelper.IsUnityCloudIntelligenceInPoc(pocRequest.Id))
                        {
                            unityPocsIds.add(pocRequest.Name);
                        }
                        
                    }
                    else
                    {
                        errorPocIds.add(string.valueof(pocRequest.Name));
                    }
                }
                catch(Exception ex)
                {
                    Database.rollback(sp);
                    SilverPeakUtils.logException(ex);
                    errorPocIds.add(string.valueof(pocRequest.Name));
                    if(successPOCIds.contains(pocRequest.Name))
                    {
                        successPOCIds.remove(pocRequest.Name);
                    }
                    continue;
                }
                
                
            }
            
            if(successPOCIds.size()>0)
            { AutomatePOCShipmentHelper.SendBatchSuccessToShipmentTeam(successPOCIds);}
            if(unityPocsIds.size()>0)
            { AutomatePOCShipmentHelper.SendUnityCloudNotifications(unityPocsIds);}
            if(errorPocIds.size()>0)
            { AutomatePOCShipmentHelper.SendErrorNotificationEmailToShipmentTeam(errorPocIds);}
            
            try
            {
                //encryp 
                List<Id> virtualLicenseIds = new List<Id>();
                for(License__c virtualLicense : [select Id from License__c where Id in :licenseIds and AssetId__r.Product2.Model__c!='GX-V' And AssetId__r.Product2.Product_Category__c !='GMS'])
                {
                    virtualLicenseIds.add(virtualLicense.Id);
                }
                if(virtualLicenseIds.size() > 0)
                {
                    AutomatePOCShipmentHelper.encryptLicenses(virtualLicenseIds);
                }
                
            }
            catch(Exception ex)
            {
                SilverPeakUtils.logException(ex); 
            }
            
            
            
            
        }
        
    }
    
    public void finish(Database.BatchableContext context)
    {
        AutomateGMSLicenseJob obj = new AutomateGMSLicenseJob();
        Database.executeBatch(obj);
    }
}