objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>License_Expiration__c</fullName>
        <label>License Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Number of GMS licenses. Always 1 for VX applinaces</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>When the license becomes active.</inlineHelpText>
        <label>License Start Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSubscriptionExpirationJobDate.cls
@isTest
public class TestSubscriptionExpirationJobDate {
     private static final Date customDate = Date.newInstance(2015, 09, 18);
    @isTest
    static void test()
    {
        
        Account acc = new Account(Name='acme');
        insert acc;
        Contact contact = new Contact(LastName='acme', AccountId=acc.Id);
        insert contact;
        Product2 product = new Product2(Name='product', Family='Virtual Image', Product_Category__c='Subscription', IsActive=true);
        insert product;
        Asset asset1 = new Asset(Name='T-30', ContactId=contact.Id, Product2Id=product.Id);
        Asset asset2 = new Asset(Name='T0', ContactId=contact.Id, Product2Id=product.Id);
        Asset asset3 = new Asset(Name='T30', ContactId=contact.Id, Product2Id=product.Id);
        Asset asset4 = new Asset(Name='T60', ContactId=contact.Id, Product2Id=product.Id);
        Asset asset5 = new Asset(Name='T90', ContactId=contact.Id, Product2Id=product.Id);
        insert new List<Asset> { asset1, asset2, asset3, asset4, asset5};
        License__c license1 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate.addDays(-30), Quantity__c=1, AssetId__c=asset1.Id);
        License__c license2 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate, Quantity__c=1, AssetId__c=asset2.Id);
        License__c license3 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate.addDays(30), Quantity__c=1, AssetId__c=asset3.Id);
        License__c license4 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate.addDays(60), Quantity__c=1, AssetId__c=asset4.Id);
        License__c license5 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate.addDays(90), Quantity__c=1, AssetId__c=asset5.Id);
        insert new List<License__c> { license1, license2, license3, license4, license5 };
        
        Test.startTest();
        Database.executeBatch(new SubscriptionExpirationReminderJobDate(), 1);
        Test.stopTest();
        
    }
    
     @isTest
    static void test_CustomerEvaluationAssets()
    {
        Account acc = new Account(Name='acme');
        insert acc;
        Contact contact = new Contact(LastName='acme', AccountId=acc.Id);
        insert contact;
        Product2 product = new Product2(Name='product', Family='Virtual Image', Product_Category__c='Subscription', IsActive=true);
        insert product;
        Asset asset1 = new Asset(Name='T-0', ContactId=contact.Id, Product2Id=product.Id,Status='Customer Evaluation');
       
        insert new List<Asset> { asset1};
        License__c license1 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate, Quantity__c=1, AssetId__c=asset1.Id);
        
        insert new List<License__c> { license1};
        
        Test.startTest();
        Database.executeBatch(new SubscriptionExpirationReminderJobDate(), 1);
        Test.stopTest();
    }
    
     @isTest
    static void test_CustomerSubscriptionAssets()
    {
        Account acc = new Account(Name='acme');
        insert acc;
        Contact contact = new Contact(LastName='acme', AccountId=acc.Id);
        insert contact;
        Product2 product = new Product2(Name='product', Family='Virtual Image', Product_Category__c='Subscription', IsActive=true);
        insert product;
        Asset asset1 = new Asset(Name='T-0', ContactId=contact.Id, Product2Id=product.Id,Status='Customer Subscription');
       
        insert new List<Asset> { asset1};
        License__c license1 = new License__c(Start_Date__c=customDate, License_Expiration__c=customDate, Quantity__c=1, AssetId__c=asset1.Id);
        
        insert new List<License__c> { license1};
        
        Test.startTest();
        Database.executeBatch(new SubscriptionExpirationReminderJobDate(), 1);
        Test.stopTest();
    }
}