objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AutomateGMSLicenseJob.cls
public class AutomateGMSLicenseJob implements Schedulable, Database.Batchable<sObject>, Database.Stateful {
    public void execute(SchedulableContext context)
    {
        Database.executeBatch(new AutomateGMSLicenseJob(), 10);
    }
    
    public Database.QueryLocator start(Database.BatchableContext context)
    {
         List<Date> lstDates= new List<Date>();
        lstDates.add(Date.today());
        lstDates.add(Date.today().addDays(-1));
        return Database.getQueryLocator([Select Id,POCRequest__c from Asset where (Product2.Model__c ='GX-V'or Product2.Product_Category__c ='GMS' )and Key_Generated__c=false and POCRequest__c in (Select Id from Request__c where Requested_Delivery_Date__c in:lstDates and  POC_Type__c='WAN Op' and Status__c='Shipped')]);
    }
    
    public void execute(Database.BatchableContext context, List<sObject> scope)
    {
        System.debug('scope.size'+scope.size());
        List<Id> lstLicenses= new List<Id>();
        Set<Id> lstPocIds= new Set<Id>();
        if(scope.size()>0)
        {
            for(sObject item :scope)
            {
                Asset assetItem= (Asset)item;
                lstPocIds.add(assetItem.POCRequest__c);
                List<License__c> lstTempLicenses= [Select Id from License__c where AssetId__c=:assetItem.Id];
                if(lstTempLicenses!=null && lstTempLicenses.size()>0)
                {
                    for(License__c licItem: lstTempLicenses)
                    {
                        lstLicenses.add(licItem.Id);
                    }
                    
                }
            }
            System.debug('LstLicenses'+lstLicenses.size());
            List<Request__c> pocRequestList =[Select Name from Request__c where Id in: lstPocIds];
            Set<string> lstPocName= new Set<String>();
            if(pocRequestList!=null && pocRequestList.size()>0)
            {
                for(Request__c pocItem :pocRequestList)
                {
                    lstPocName.add(pocItem.Name);
                }
                
            }
            try
            {
                AutomatePOCShipmentHelper.encryptLicenses(lstLicenses);
            }
            catch(Exception ex)
            {
                SilverPeakUtils.logException(ex); 
            }
            
            AutomatePOCShipmentHelper.SendGMSLicenseStatusToShipmentTeam(lstPocName);
        }
    }
    
    public void finish(Database.BatchableContext context)
    {
        if(!Test.isRunningTest())
        {	
             AutomateVirtualPOCBatch obj= new AutomateVirtualPOCBatch();
        	 System.scheduleBatch(obj, 'Automate POC Shipments', 15);
        }
       
        
    }
}