objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_for_Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Sends an email to this contact when new license keys are generated</inlineHelpText>
        <label>Contact for Notification</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>License Key for Virtual Appliances or GMS</description>
        <inlineHelpText>Don&apos;t edit this field, or the key may not work!</inlineHelpText>
        <label>Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiration__c</fullName>
        <label>License Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Number of GMS licenses. Always 1 for VX applinaces</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SerialNumber__c</fullName>
        <label>Serial Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>When the license becomes active.</inlineHelpText>
        <label>License Start Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GenerateGmsLicenseController.cls
/*
 * Controller of page GenerateGxLicense
 */
public with sharing class GenerateGmsLicenseController 
{
    private Asset assetRecord;
    
    public GenerateGmsLicenseController(ApexPages.StandardController controller)
    {
        assetRecord = (Asset)controller.getRecord();
        InProgress = false;
        if(assetRecord.Product2.Product_Category__c != 'GMS' && assetRecord.Product2.Model__c != 'GX-V')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'You can only generate GMS license on a GMS asset.'));
        }
        License = new License__c(AssetId__c=assetRecord.Id, SerialNumber__c=assetRecord.SerialNumber, Model__c=assetRecord.Model__c, Start_Date__c=assetRecord.Evaluation_Start_Date__c, License_Expiration__c=assetRecord.Evaluation_End_Date__c, Contact_for_Notification__c=assetRecord.ContactId);
        try
        {
            License.Quantity__c= Integer.valueOf(assetRecord.GMS_Nodes__c);
        }
        catch(Exception ex)
        {
        }
    }

    public License__c License { get; set; }
    public Boolean InProgress { get; set; }
    
    public PageReference save()
    {
        try
        {
            upsert License;
            update new Asset(Id=assetRecord.Id, GMS_Nodes__c=String.valueOf(License.Quantity__c), GMS_Upgrading__c=true);
            VirtualAssetManager.encryptLicense(License.Id);
            InProgress = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'License is being generated...'));
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
        }
        return null;
    }
    
    @remoteAction
    public static Boolean hasLicenseGenerated(String licenseId)
    {
        List<License__c> licenses = [select Key__c from License__c where Id=:licenseId limit 1];
        if(licenses.size() > 0)
        {
            return String.isNotBlank(licenses[0].Key__c);
        }
        return null;
    }
}