objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AssetId__c</fullName>
        <label>Serial Number</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>License Key for Virtual Appliances or GMS</description>
        <inlineHelpText>Don&apos;t edit this field, or the key may not work!</inlineHelpText>
        <label>Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LicenseKeyForVirtualAssetController.cls
/* 
 * Controller for component LiccenseKeyForVirtualAsset
 */
public class LicenseKeyForVirtualAssetController
{
    public Integer LicenseIndex { get; set; }
    public Id AssetId { get; set; }
    public String LicenseKey
    {
        get
        {
            List<License__c> licenses = [select Id, Key__c from License__c where AssetId__c=:AssetId order by CreatedDate limit 1 offset :LicenseIndex];
            if(licenses.size() > 0)
            {
                return licenses[0].Key__c;
            }
            return '';
        }
    }
    
    @isTest
    static void testLicenseKeyForVirtualAssetController()
    {
        Account acc = new Account(Name='acme');
        insert acc;
        Asset asset = new Asset(Name='acme', AccountId=acc.Id);
        insert asset;
        License__c l1 = new License__c(AssetId__c=asset.Id, Key__c='1');
        License__c l2 = new License__c(AssetId__c=asset.Id, Key__c='2');
        insert l1;
        insert l2;
        
        LicenseKeyForVirtualAssetController controller = new LicenseKeyForVirtualAssetController();
        controller.AssetId = asset.Id;
        controller.LicenseIndex = 1;
        System.assertEquals('2', controller.LicenseKey);
    }
}