objects/LMS_Course_Certification__c.object
<CustomObject>
    <fields>
        <fullName>Certification_ID__c</fullName>
        <label>Certification Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certification_Title__c</fullName>
        <label>Certification Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Id__c</fullName>
        <label>Course Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Learner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Display_Name__c</fullName>
        <label>Status Display Name</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <label>Student Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validity_Date__c</fullName>
        <label>Validity Date</label>
        <type>Date</type>
    </fields>
    <label>LMS Course Certification</label>
    <nameField>
        <displayFormat>CRT-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LMSFetchCertificationDetailsBatch.cls
public class LMSFetchCertificationDetailsBatch implements Database.Batchable<sObject>,Database.Stateful, Database.AllowsCallouts{
    private  Integer recordCount = 0;
    public Database.QueryLocator start(Database.BatchableContext context)
    {
        return Database.getQueryLocator([Select Id,Certification_ID__c,Course_Id__c from LMS_Course_Certification__c where Status_Display_Name__c='Sync Pending']);
    }
    
    public void execute(Database.BatchableContext context, List<sObject> scope)
    {
        List<LMS_Course_Certification__c> lstCertificatesDtl= (List<LMS_Course_Certification__c>) scope;
        
        List<LMS_Course_Certification__c> lstCertToUpdate= new List<LMS_Course_Certification__c>();
        string token=null;
        if(Test.isRunningTest())
        {
            token='****';
        }
        if(lstCertificatesDtl!=null && lstCertificatesDtl.size()>0)
        {
            recordCount += lstCertificatesDtl.size();
            for(LMS_Course_Certification__c item: lstCertificatesDtl)
            {
                
                PartnerPortalGetCourseCertificateApi courseCertAPI = new PartnerPortalGetCourseCertificateApi(item.Certification_ID__c,String.valueOf(item.Course_Id__c),token);
                courseCertAPI.execute();
                if(courseCertAPI.CourseCertificate!=null)
                {
                    PartnerPortalCourseCertficate cert= courseCertAPI.CourseCertificate;
                    item.Certification_Title__c= cert.Title;
                    item.Status__c= cert.Status;
                    item.Student_Id__c= cert.studentsId;
                    item.Expiry_Date__c= Date.valueOf(cert.expires);
                    item.Validity_Date__c= Date.valueOf(cert.valid);
                    string statusDisp= cert.StatusDisplay;
                    if(String.isBlank(statusDisp))
                    {
                        statusDisp='Sync Complete';
                    }
                    else if(item.Expiry_Date__c<Date.today())
                    {
                        statusDisp='Expired';
                    }
                    else
                    {  
                        statusDisp='Active';
                    }
                    item.Status_Display_Name__c=statusDisp ;
                    lstCertToUpdate.add(item);
                } 
            }
        }
        
        try
        {
            if(lstCertToUpdate.size()>0)
            {
                
                update lstCertToUpdate;
                
            }
        }
        catch(Exception ex)
        {
            SilverPeakUtils.logException(ex);
        }
    }
    
    public void finish(Database.BatchableContext context)
    {
        insert new ErrorLog__c(Subject__c='LMS Certifications Sync Pending ', Message__c='There are ' + recordCount + ' certifications in sync Pending status.');
        LMSBatchHelper.AssociateContactwithEachCertUsingStudentId();
        LMSBatchHelper.AssociateContactwithEachCertUsingStudentEmail();
        List<LMS_Course_Certification__c> lstCertWithNoEmail= [Select Id,Learner_Contact__c,Student_Id__c from LMS_Course_Certification__c where Learner_Contact__c=null and Student_Email__c=null];
        if(lstCertWithNoEmail!=null && lstCertWithNoEmail.size()>0)
        {
            insert new ErrorLog__c(Subject__c='LMS Certifications By Email ', Message__c='There are ' + lstCertWithNoEmail.size() + ' certifications populated by email.');
        }
       	LMSAssociateLearnerContactByEmail obj = new LMSAssociateLearnerContactByEmail();
        Database.executeBatch(obj,1);
        
    }
}