objects/LMS_Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Id__c</fullName>
        <label>Course Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>LMS Course</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMS Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LMS_Course_Certification__c.object
<CustomObject>
    <fields>
        <fullName>Certification_ID__c</fullName>
        <label>Certification Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Id__c</fullName>
        <label>Course Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LMS_Course_Id__c</fullName>
        <label>LMS Course Id</label>
        <referenceTo>LMS_Course__c</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status_Display_Name__c</fullName>
        <label>Status Display Name</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LMS Course Certification</label>
    <nameField>
        <displayFormat>CRT-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestLMSUpdateCertExpiredSchedule.cls
@IsTest
public class TestLMSUpdateCertExpiredSchedule {
    
    @IsTest
    public static void UpdateExpiredRecords()
    {
        LMS_Course__c course= new LMS_Course__c(Course_Id__c='233333',Course_Name__c='Test Course',Display_Name__c='Test Course Display Name',Is_Active__c=true);
        insert course;
        LMS_Course_Certification__c cert= new LMS_Course_Certification__c(Certification_ID__c='123232323',LMS_Course_Id__c=course.Id,Status_Display_Name__c='Active',Expiry_Date__c=Date.today().addDays(-1));
        insert cert;
        LMSUpdateCertExpiredSchedule obj= new LMSUpdateCertExpiredSchedule();
        obj.execute(null);
        LMS_Course_Certification__c certResult=[Select Status_Display_Name__c from LMS_Course_Certification__c where Id=:cert.Id ];
        System.assertEquals('Expired',certResult.Status_Display_Name__c);
    }
    
}