objects/LMS_Course_Certification__c.object
<CustomObject>
    <fields>
        <fullName>Certification_ID__c</fullName>
        <label>Certification Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Id__c</fullName>
        <label>Course Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Display_Name__c</fullName>
        <label>Status Display Name</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LMS Course Certification</label>
    <nameField>
        <displayFormat>CRT-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LMSUpdateCertExpiredSchedule.cls
public class LMSUpdateCertExpiredSchedule implements Schedulable {
    public void execute(SchedulableContext context)
    {
        List<LMS_Course_Certification__c> lstCertificatesDtl=[ Select Id,Certification_ID__c,Course_Id__c from LMS_Course_Certification__c where Status_Display_Name__c='Active' and Expiry_Date__c<:Date.today()];
        List<LMS_Course_Certification__c> lstCertificatesToUpdate = new List<LMS_Course_Certification__c>();
        if(lstCertificatesDtl!=null && lstCertificatesDtl.size()>0)
        {
            for(LMS_Course_Certification__c cert:lstCertificatesDtl)
            {
                cert.Status_Display_Name__c='Expired';
                lstCertificatesToUpdate.add(cert);
            }
        }
        if(lstCertificatesToUpdate.size()>0)
        {
            update lstCertificatesToUpdate;
        }
    }
}