objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <inlineHelpText>Use: xx/xx/xxxx date format or the date picker</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsubmitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDF_Status__c</fullName>
        <label>MDF Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Program__c</fullName>
        <label>Type of Program</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement - 1/2 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - 1/4 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - Full page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast (Television/Radio)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral/Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Blast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eNewletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Incentives/Promotional Contest/Giveaways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telemarketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Industry Shows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendEmailAndCreateCampaignTest.cls
/*
 * Test for the SendUrlToUser
 * 23/8/2016 @Author Daniel Wu
 *
 */
@isTest
public class SendEmailAndCreateCampaignTest {
    @isTest
	public static void testSendEmailAndCreateCampaign()
    {
        List<User> currentUser = [Select Id, Profile.Name, Profile.Id, Name from User where Profile.Name != '13g-SP Partner Community' and IsActive = true limit 1];
        if(currentUser.isEmpty())
        {
            return;
        }
        Contact con = new Contact(LastName='Acme', Email='acme@test.com',FirstName='Acme');
        insert con;
        MDF_Request__c mdf = new MDF_Request__c(Type_of_Program__c ='Awareness', OwnerId = currentUser[0].Id, Contact__c = con.Id, Activity_Date__c = date.today());
        insert mdf;
        MDF_Request__c newMDF = [Select Id, Approval_status__c,Activity_Complete__c, MDF_Status__c, SendReminder__c from MDF_Request__c where Id =: mdf.Id];
        newMDF.Approval_Status__c = 'Approved';
        newMDF.Activity_Complete__c = false;
        newMDF.MDF_Status__c = 'Past Due';
        newMDF.SendReminder__c = true;
		Test.startTest();
        update newMDF;
        Test.stopTest();
		mdf = [Select Id, Campaign__c from MDF_Request__c where Id =: newMDF.Id];
		system.assertEquals(1, [Select Count() from Campaign where Id =: mdf.Campaign__c]);
    }
}