objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <inlineHelpText>Use: xx/xx/xxxx date format or the date picker</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsubmitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendEmailAlertHWhenMDFisPastDue.cls
global class SendEmailAlertHWhenMDFisPastDue implements Schedulable 
{
    global void execute(SchedulableCOntext sc)
    {
    	sendEmailAlert();
    }
    public void sendEmailAlert()
    {
    	List<MDF_Request__c> mdfs = [Select Id, Name, Owner.Name, Owner.Email from MDF_Request__c where Approval_Status__c = 'Approved' and Activity_Date__c > Today and Activity_complete__c = false ];
        if(!mdfs.isEmpty())
        {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        	for(MDF_Request__c mdf : mdfs )
            {
                Blob cryptoData = Crypto.encryptWithManagedIV('AES128', Blob.valueOf('DanielMDfURLToUs'), Blob.valueOf(mdf.Id + '|' + Date.today().format()));
                String url = EncodingUtil.base64Encode(cryptoData).replaceAll('\\+', '%2B');
                List<String> toAddress = new String[]{'daniel@snapbi.com'};
                mail.setReplyTo('wt_1993@foxmial.com');
                mail.setSenderDisplayName('The Silver Peak Team');
                mail.setSubject('Silver Peak MDF Request ' + mdf.Name + ' is Past Due');
                mail.setBccSender(false);
                mail.setUseSignature(false);
                mail.setHtmlBody('Dear ' + mdf.Owner.Name+ ',<br/><br/> Your Request Fund has been created: <a href="https://full-silverpeak.cs51.force.com/s/MarketingFundsAnonymous?id='+ url +'">'+ mdf.Name +'</a> Please complete this request.<br/><br/>If you have any questions, please contact your local Channel Sales Manager or e-mail us at channel@silver-peak.com.<br/><br/>Sincerely, <br/><br/>Silver Peak Channel Marketing');
                mail.setToAddresses(toAddress);
                mails.add(mail);
            }
            Messaging.sendEmail(mails);
        }
        
        
    }
}