objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <inlineHelpText>Use: xx/xx/xxxx date format or the date picker</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsubmitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Campaign_Name__c</fullName>
        <label>Event/Campaign Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GEO__c</fullName>
        <label>GEO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Status__c</fullName>
        <label>MDF Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <formula>Submitter__r.Account.Name</formula>
        <label>Partner Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Program__c</fullName>
        <label>Type of Program</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement - 1/2 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - 1/4 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - Full page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast (Television/Radio)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral/Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Blast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eNewletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Incentives/Promotional Contest/Giveaways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telemarketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Industry Shows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PartnerMDFListingController.cls
public class PartnerMDFListingController {
    public list<MDF_Request__c> Requests{ get; set; }
    public PartnerMDFListingController()
    {
        Requests = [Select Id, Name,Type_of_Program__c , Event_Campaign_Name__c, Activity_Date__c, Activity_Complete__c, Partner_Account__c, GEO__c, 
                    MDF_Status__c, Approval_Status__c from MDF_Request__c where OwnerId =: UserInfo.getUserId() order by Activity_Date__c Desc NULLS LAST];
    }
}