objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsubmitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Est_Value_of_Expected_Opportunities__c</fullName>
        <inlineHelpText>Estimated Value of Expected Opportunities</inlineHelpText>
        <label>Est Value of Expected Opportunities</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Location_City__c</fullName>
        <label>Event Location (City)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location_Zip__c</fullName>
        <label>Event Location (Zip)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Audience_Size__c</fullName>
        <label>Expected Audience Size</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Number_of_Leads__c</fullName>
        <label>Expected Number of Leads</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Program__c</fullName>
        <label>Type of Program</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement - 1/2 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - 1/4 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - Full page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast (Television/Radio)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral/Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Blast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eNewletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Incentives/Promotional Contest/Giveaways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telemarketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Industry Shows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MarketingFundsControllerTest.cls
@isTest
public class MarketingFundsControllerTest {
    @isTest
    public static void testAnonymousUser()
    {
        List<User> crrentUser = [Select Id from User where Profile.Name = 'Silver Peak Partner Community Profile' limit 1];
        if(crrentUser.isEmpty())
        {
            return;
        }
        system.runAs(crrentUser[0])
        {
            MarketingFundsController mfc1 = new MarketingFundsController();
            mfc1.pap1.Country__c = 'USA';
            mfc1.pap1.State__c = 'California';
            mfc1.eventDetails = 'test;test;';
            mfc1.saveMDF();
            mfc1.saveApprovedMDF();
            
            MDF_Request__c mdf = new MDF_Request__c(Type_of_Program__c ='Awareness', Event_Materials_Requested__c = 'test\r\nmessage',
                                                    Silver_Peak_Speaking_Opportunity__c = 'Yes');
            insert mdf;
            List<Attachment> atts = new List<Attachment>();
            Attachment accountAttachment = new Attachment(Name = 'Test', Body = Blob.valueOf('Test Data'), Description = 'Target Account List', ParentId = mdf.Id);
            atts.add(accountAttachment);
            Attachment eventAgendaAttachment = new Attachment(Name = 'Test', Body = Blob.valueOf('Test Data'), Description = 'Event Agenda',ParentId = mdf.Id);
            atts.add(eventAgendaAttachment);
            Attachment invoice = new Attachment(Name = 'Test', Body = Blob.valueOf('Test Data'), Description = 'invoice', ParentId = mdf.Id);
            atts.add(invoice);
            Attachment proof = new Attachment(Name = 'Test', Body = Blob.valueOf('Test Data'), Description = 'proof', ParentId = mdf.Id);
            atts.add(proof);
           	Attachment attendance = new Attachment(Name = 'Test', Body = Blob.valueOf('Test Data'), Description = 'attendance', ParentId = mdf.Id);
            atts.add(attendance);
            insert atts;
            Blob cryptoData = Crypto.encryptWithManagedIV('AES128', Blob.valueOf('SliverPeakCrytpo'), Blob.valueOf(mdf.Id + '|' + Date.today().format()));
            String url = EncodingUtil.base64Encode(cryptoData);
            ApexPages.currentPage().getParameters().put('id',url);
            MarketingFundsController mfc = new MarketingFundsController();
            mfc.pap1.Country__c = '';
            mfc.pap1.State__c = '';
            mfc.saveMDF();
            mfc.saveApprovedMDF();
            
            MarketingFundsController mfc2 = new MarketingFundsController();
            mfc2.accountAttachment.Body = Blob.valueOf('Test Data');
            mfc2.eventAgendaAttachment.Body = Blob.valueOf('Test Data');
            mfc2.request = new MDF_Request__c(Type_of_Program__c ='Awareness', Silver_Peak_Speaking_Opportunity__c = 'No', Approval_Status__c = 'Approved', Activity_Complete__c = true,Expected_Audience_Size__c = 2, Expected_Number_of_Leads__c = 2,Est_Value_of_Expected_Opportunities__c = 2,Event_Location_City__c = 'los', Event_Location_Zip__c = 'testZip');
            mfc2.pap1.Country__c = 'USA';
            mfc2.pap1.State__c = 'California';
            system.assertEquals(true, mfc2.validateFileds());
            try
            {
                mfc2.saveMDF();
            }
            catch(Exception ex)
            {
                ex.getMessage();
            }
            mfc2.saveApprovedMDF();
        }
    }
    
    @isTest
    public static void testLoginUser()
    {
        MarketingFundsController mfc1 = new MarketingFundsController();
        mfc1.pap1.Country__c = 'USA';
        mfc1.pap1.State__c = 'California';
        mfc1.eventDetails = 'test;test;';
        mfc1.saveMDF();
        mfc1.saveApprovedMDF();

        MDF_Request__c mdf = new MDF_Request__c(Type_of_Program__c ='Awareness', Event_Materials_Requested__c = 'test\r\nmessage',
                                                Silver_Peak_Speaking_Opportunity__c = 'Yes');
        insert mdf;
        ApexPages.currentPage().getParameters().put('id',mdf.id);
        MarketingFundsController mfc = new MarketingFundsController();
        mfc.pap1.Country__c = '';
        mfc.pap1.State__c = '';
        mfc.invoice.Body = Blob.valueOf('Test Data');
        mfc.invoice.Name = 'test';
        mfc.proof.Body = Blob.valueOf('Test Data');
        mfc.proof.Name = 'Test';
        mfc.attendance.Body = Blob.valueOf('Test Data');
        mfc.attendance.Name = 'Test';
        mfc.saveMDF();
        mfc.saveApprovedMDF();

        MarketingFundsController mfc2 = new MarketingFundsController();
        mfc2.accountAttachment.Body = Blob.valueOf('Test Data');
        mfc2.eventAgendaAttachment.Body = Blob.valueOf('Test Data');
		mfc2.accountAttachment.Name = 'Test';
        mfc2.eventAgendaAttachment.Name = 'Test';
        mfc2.request = new MDF_Request__c(Type_of_Program__c ='Awareness', Silver_Peak_Speaking_Opportunity__c = 'No', Approval_Status__c = 'Approved', Activity_Complete__c = true,Expected_Audience_Size__c = 2, Expected_Number_of_Leads__c = 2,Est_Value_of_Expected_Opportunities__c = 2,Event_Location_City__c = 'los', Event_Location_Zip__c = 'testZip');
        mfc2.pap1.Country__c = 'USA';
        mfc2.pap1.State__c = 'California';
        system.assertEquals(true, mfc2.validateFileds());
        try
        {
            mfc2.saveMDF();
        }
        catch(Exception ex)
        {
        }
        mfc2.saveApprovedMDF();  
    }
    
    @isTest
    public static void testPartnerController()
    {
        PartnerMDFListingController pmc = new PartnerMDFListingController();
    }
}