objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Accounting_PoC_Email__c</fullName>
        <label>Accounting PoC: Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Accounting_PoC_Name__c</fullName>
        <label>Accounting PoC: Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <inlineHelpText>Use: xx/xx/xxxx date format or the date picker</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Partner_Cost__c</fullName>
        <label>Actual Partner Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Program_Cost__c</fullName>
        <label>Actual Program Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Addl_Vendor_1__c</fullName>
        <label>Vendor 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Addl_Vendor_2__c</fullName>
        <label>Vendor 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Addl_Vendor_3__c</fullName>
        <label>Vendor 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsubmitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Est_Value_of_Expected_Opportunities__c</fullName>
        <inlineHelpText>Estimated Value of Expected Opportunities</inlineHelpText>
        <label>Est Value of Expected Opportunities</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Other_Vendor_s_Amount__c</fullName>
        <label>Estimated Other Vendor(s) Amount:</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Partner_Amount__c</fullName>
        <label>Estimated Partner Amount</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Pipeline_Value__c</fullName>
        <label>Estimated Pipeline Value</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Silver_Peak_Amount__c</fullName>
        <label>Estimated Silver Peak Amount</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Campaign_Name__c</fullName>
        <label>Event/Campaign Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Granted_Reason__c</fullName>
        <label>Exception Granted Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Audience_Size__c</fullName>
        <label>Expected Audience Size</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Number_of_Leads__c</fullName>
        <label>Expected Number of Leads</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fast_Start_Marketing_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fast Start Marketing Program?</inlineHelpText>
        <label>Fast Start Marketing Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Industry_Vertical_Being_Targeted__c</fullName>
        <inlineHelpText>Industry/Vertical Being Targeted</inlineHelpText>
        <label>Industry/Vertical Being Targeted</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_No__c</fullName>
        <label>Invoice No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_of_Event__c</fullName>
        <inlineHelpText>Location of Event(City or Geography Targeted):</inlineHelpText>
        <label>Location of Event</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Activity_PoC_Email__c</fullName>
        <label>Marketing Activity PoC: Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Marketing_Activity_Point_of_Contact_Nam__c</fullName>
        <inlineHelpText>Point of Contact for Marketing</inlineHelpText>
        <label>Marketing Activity PoC: Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PO_No__c</fullName>
        <label>PO No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_at_Platinum_Level__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Partner at Platinum Level?</inlineHelpText>
        <label>Partner at Platinum Level</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purchasing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchasing Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Purchasing_Request__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>MDF Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Purchasing_Request__c</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quarterly_Marketing_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Included In Joint Quarterly Marketing Plan?</inlineHelpText>
        <label>Quarterly Marketing Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_Rejected__c</fullName>
        <label>Reason Denied</label>
        <picklist>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Venue/Topic to Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate MDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Generally Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Remit_Address_1__c</fullName>
        <label>Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Address_2__c</fullName>
        <label>Address 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result_Detail__c</fullName>
        <label>Result Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Submitted_For__c</fullName>
        <label>Submitted For</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to pull the submitters information onto the request form</description>
        <label>Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Audience_Profile__c</fullName>
        <label>Target Audience Profile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Attendees__c</fullName>
        <label>Total Attendees</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Program_Costs__c</fullName>
        <label>Total Estimated Program Costs</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Leads_Generated__c</fullName>
        <label>Total Leads Generated</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Qualified_Leads__c</fullName>
        <label>Total Qualified Leads</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Program__c</fullName>
        <label>Type of Program</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement - 1/2 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - 1/4 page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement - Full page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast (Television/Radio)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral/Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Blast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eNewletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Incentives/Promotional Contest/Giveaways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telemarketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Industry Shows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>post_event_follow_up_plan__c</fullName>
        <inlineHelpText>What is your post event follow up plan?</inlineHelpText>
        <label>What is your post event follow up plan?</label>
        <type>TextArea</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Purchasing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchasing Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>PR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchasing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerPortalRequestMDFController.cls
/*
 * Controller class of VF pages related to MDF request
 */
public class PartnerPortalRequestMDFController
{
    public PartnerPortalRequestMDFController()
    {
        User currentUser = [select Id, ContactId from User where Id=:UserInfo.getUserId() limit 1];
        List<Contact> contacts = [select Id, Name, Email, Phone, AccountId, Account.Name, Account.ShippingStreet, Account.ShippingCity, Account.ShippingState, Account.ShippingPostalCode, Account.ShippingCountry from Contact where Id=:currentUser.ContactId limit 1];
        currentContact = (contacts.size() > 0) ? contacts[0] : new Contact();
        Id currentAccountId = (contacts.size() > 0) ? contacts[0].AccountId : null;
        
        String requestId = ApexPages.currentPage().getParameters().get('id');
        if(String.isNotBlank(requestId))
        {
            List<MDF_Request__c> requests = [select Id, Name, Purchasing_Request__c, Type_of_Program__c, Event_Campaign_Name__c, Location_of_Event__c, Activity_Date__c, Target_Audience_Profile__c, Industry_Vertical_Being_Targeted__c, Expected_Audience_Size__c, Expected_Number_of_Leads__c, Est_Value_of_Expected_Opportunities__c, 
                                            Addl_Vendor_1__c, Addl_Vendor_2__c, Addl_Vendor_3__c, Total_Estimated_Program_Costs__c, Estimated_Partner_Amount__c, Estimated_Silver_Peak_Amount__c, Estimated_Other_Vendor_s_Amount__c, post_event_follow_up_plan__c, Comments__c, Submitted_For__c, Submitter__r.AccountId,
                                            Marketing_Activity_Point_of_Contact_Nam__c, Marketing_Activity_PoC_Email__c, Accounting_PoC_Name__c, Accounting_PoC_Email__c, Remit_Address_1__c, Remit_Address_2__c, Remit_City__c, Remit_State__c, Remit_Zip_Postal_Code__c, Remit_Country__c, CreatedDate, CreatedbyId,
                                            Approval_Date__c, Approval_Status__c, Invoice_No__c, PO_No__c, Quarterly_Marketing_Plan__c, Fast_Start_Marketing_Program__c, Partner_at_Platinum_Level__c, Exception_Granted_Reason__c, Reason_Rejected__c, Activity_Complete__c, Result_Detail__c, 
                                            Total_Attendees__c, Total_Leads_Generated__c, Total_Qualified_Leads__c, Estimated_Pipeline_Value__c, Actual_Program_Cost__c, Actual_Partner_Cost__c, Requested_Reimbursement_Amount__c, Additional_Vendor_Cost_1__c, Additional_Vendor_Cost_2__c 
                                            from MDF_Request__c where Name=:requestId limit 1];
            request = (requests.size() > 0) ? requests[0] : new MDF_Request__c(Account__c=currentAccountId);
            initAttachments(request.Id);
        } 
        else
        {
            request = new MDF_Request__c(Account__c=currentAccountId);
            filterField = 'Activity_Date__c';
            filterValue = 'THIS_QUARTER';
            sortField = 'Activity_Date__c';
            search();
            initAttachments(null);
        }
    }
    
    public Contact currentContact { get; set; }
    public MDF_Request__c request { get; set; }
    public Attachment invoiceAttachment { get; set; }
    public Attachment proofAttachment { get; set; }
    public Attachment attlistAttachment { get; set; }
    public Attachment sampleAtachment { get; set; }
    public Attachment eventAttachment { get; set; }
    public Attachment addlAttachment1 { get; set; }
    public Attachment addlAttachment2 { get; set; }
    public Attachment addlAttachment3 { get; set; }
    
    public String keyword { get; set; }
    public String filterField { get; set; }
    public String filterValue { get; set; }
    public String sortField { get; set; }
    public List<MDF_Request__c> requests { get; private set; }
    
    public Boolean isInitial { get { return String.isBlank(request.Approval_Status__c) || request.Approval_Status__c == 'Unsubmitted'; }}
    public Boolean isSubmitted { get { return request.Approval_Status__c == 'Pending'; } }
    public Boolean isDenied { get { return request.Approval_Status__c == 'Denied'; } }
    public Boolean isApproved { get { return request.Approval_Status__c == 'Approved'; }}
    
    public PageReference authorize() 
    {
        User currentUser = [select Id, ContactId from User where Id=:UserInfo.getUserId() limit 1];
        List<Contact> contacts = [select Id, Name, Email, Phone, AccountId, Account.Name, Account.ShippingStreet, Account.ShippingCity, Account.ShippingState, Account.ShippingPostalCode, Account.ShippingCountry from Contact where Id=:currentUser.ContactId limit 1];
        currentContact = (contacts.size() > 0) ? contacts[0] : new Contact();
        
        if(request.Id != null && request.Submitter__r.AccountId != currentContact.AccountId && request.CreatedById != UserInfo.getUserId())
        {
            request = new MDF_Request__c();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'MDF does not exist or you are not authorized to view this record.'));
        }
        else
        {
            Database.insert(new MDF_Request__Share(ParentId=request.Id, UserOrGroupId=UserInfo.getUserId(), AccessLevel='Edit'), false);
        }
        return null;
    }
    
    public PageReference search()
    {
        try
        {
            if(String.isNotBlank(keyword) && keyword.length() >= 2)
            {
                String sosl = 'find :keyword returning MDF_Request__c(Id, Name, Type_of_Program__c, Activity_Complete__c, Approval_Status__c, Invoice_No__c, PO_No__c, Estimated_Silver_Peak_Amount__c, Activity_Date__c, Event_Campaign_Name__c where (Submitter__r.AccountId=\''+currentContact.AccountId+'\' or CreatedById=\''+UserInfo.getUserId()+'\') and ' + filterField +'=' + filterValue + ' order by ' + sortField + ' limit 1000)';
                requests = Search.query(sosl)[0];
            }
            else
            {
                String soql = 'select Id, Name, Type_of_Program__c, Activity_Complete__c, Approval_Status__c, Invoice_No__c, PO_No__c, Estimated_Silver_Peak_Amount__c, Activity_Date__c, Event_Campaign_Name__c from MDF_Request__c where (Submitter__r.AccountId=\''+currentContact.AccountId+'\' or CreatedById=\''+UserInfo.getUserId()+'\') and ';
                soql += filterField +'=' + filterValue;
                soql += ' order by ' + sortField;
                soql += ' limit 1000';
                requests = Database.query(soql);
            }
        }
        catch(Exception ex)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Error occured while searching. Please retry.'));
        }
        return null;
    }
    
    public PageReference deleteAttachment()
    {
        String fileId = ApexPages.currentPage().getParameters().get('file');
        if(String.isNotBlank(fileId) && fileId instanceOf Id && fileId.startsWith('00P'))
        {
            try
            {
                delete new Attachment(Id=fileId);
                initAttachments(request.Id);
            }
            catch(Exception ex)
            {
                ApexPages.addMessages(ex);
            }
        }
        return null;
    }
    
    public PageReference save()
    {
        Boolean isSucceeded = true;
        SavePoint sp = Database.setSavePoint();
        try
        {
            saveRequestAndAttachments();
        }
        catch(Exception ex)
        {
            isSucceeded = false;
            Database.rollback(sp);
            ApexPages.addMessages(ex);
            return null;
        }
        
        //Send Email Notification when MDF is updated or attachments are uploaded.
        if(isApproved || isSubmitted)
        {
            isSucceeded = sendEmailNotification();
        }
        
        if(isSucceeded) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'MDF Request is saved. '));
        }
        return null;
    }
    
    public PageReference submit()
    {
        SavePoint sp = Database.setSavePoint();
        if(request.Id == null || request.Purchasing_Request__c == null)
        {
            try
            {
                saveRequestAndAttachments();
            }
            catch(Exception ex)
            {
                Database.rollback(sp);
                ApexPages.addMessages(ex);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getStackTraceString()));
                return null;
            }
        }
        
        try
        {
            updateCSM();
            Approval.ProcessSubmitRequest process = new Approval.ProcessSubmitRequest();
            process.setComments('Client submission');
            process.setObjectId(request.Id);
            Approval.ProcessResult result = Approval.process(process);
            if(result.getInstanceStatus() == 'Pending')
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'MDF Request is submitted.'));
                return Page.PartnerPortalManageMDF;
            }
            else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, result.getInstanceStatus()));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Failed to submit this request.'));
            }
        }
        catch(Exception ex)
        {
            Database.rollback(sp);
            ApexPages.addMessages(ex);
        }
        return null;
    }
    
    private void saveRequestAndAttachments()
    {
        if(request.Purchasing_Request__c == null)
        {
            List<RecordType> purchaseRecordType = [select Id from RecordType where SobjectType='Purchasing_Request__c' and Name='MDF Request' limit 1];
            Purchasing_Request__c purchase = new Purchasing_Request__c();
            purchase.RecordTypeId = (purchaseRecordType.size() > 0) ? purchaseRecordType[0].Id : null;
            insert purchase;
            request.Purchasing_Request__c = purchase.Id;
        }
        upsert request;
        
        List<Attachment> attachments = new List<Attachment>();
        addAttachmentToList(invoiceAttachment, request.Id, attachments);
        addAttachmentToList(proofAttachment, request.Id, attachments);
        addAttachmentToList(attlistAttachment, request.Id, attachments);
        addAttachmentToList(sampleAtachment, request.Id, attachments);
        addAttachmentToList(eventAttachment, request.Id, attachments);
        addAttachmentToList(addlAttachment1, request.Id, attachments);
        addAttachmentToList(addlAttachment2, request.Id, attachments);
        addAttachmentToList(addlAttachment3, request.Id, attachments);
        if(attachments.size() > 0)
        {
            upsert attachments;
            initAttachments(request.Id);
        }
    }

    //Constant for sending email notification.
    static final String EMAIL_TEMPLATE_NAME = 'MDF_Update_Email';
    static final String ORG_WIDE_EMAILL_ADDRESS_NAME = 'Silver Peak Notifications';
    static final String TO_ADDRESS = 'marketingrequest@silver-peak.com';
    static final List<String> CC_ADDRESSES = new List<String> { 'amenjivar@silver-peak.com', 'sstrachman@silver-peak.com' };

    private Boolean sendEmailNotification()
    {
        Boolean isSucceeded = true;
        List<EmailTemplate> emailTemplates = [select Id from EmailTemplate where DeveloperName = :EMAIL_TEMPLATE_NAME];
        List<OrgWideEmailAddress> orgWideEmailAddresses = [select Id from OrgWideEmailAddress where DisplayName = :ORG_WIDE_EMAILL_ADDRESS_NAME];
        if(emailTemplates.size() > 0 && orgWideEmailAddresses.size() > 0) {
            Contact tempContact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = TO_ADDRESS);
            insert tempContact; //For sending email.

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setOrgWideEmailAddressId(orgWideEmailAddresses[0].Id);
            mail.setTemplateId(emailTemplates[0].Id);
            mail.setCcAddresses(CC_ADDRESSES);
            mail.setWhatId(request.Id);
            mail.setTargetObjectId(tempContact.Id);
            mail.setSaveAsActivity(false);
            try
            {
                Messaging.sendEmail(new List<Messaging.SingleEmailMessage> { mail });
            }
            catch(Exception ex)
            {
                ApexPages.addMessages(ex);
                isSucceeded = false;
            }
            delete tempContact;
        }
        return isSucceeded;
    }
    
    private void updateCSM()
    {
        List<Account> currentAccount = [select Id, OwnerId, Owner.GEO_Region__c, Patch__c, Patch__r.CSM__c, Patch__r.CSM__r.GEO_Region__c, Patch__r.RSM__c, Patch__r.RSM__r.GEO_Region__c from Account where Id=:currentContact.AccountId limit 1];
        if(currentAccount.size() > 0)
        {
            request.CSM__c = currentAccount[0].Patch__r.CSM__c;
            request.RSM__c = currentAccount[0].Patch__r.RSM__c;
            request.GEO__c = currentAccount[0].Patch__r.CSM__r.GEO_Region__c;
            if(request.CSM__c == null)
            {
                request.CSM__c = currentAccount[0].OwnerId;
            }
            if(request.RSM__c == null)
            {
                request.RSM__c = currentAccount[0].OwnerId;
            }
            if(String.isBlank(request.GEO__c))
            {
                request.GEO__c = currentAccount[0].Owner.GEO_Region__c;
            }
            if(String.isNotBlank(request.GEO__c))
            {
                String geo = request.GEO__c;
                String[] parts = geo.split('-');
                if(parts.size() >= 1)
                {
                    request.GEO__c = parts[0];
                }
            }
        }
        request.Submitter__c = currentContact.Id;
        upsert request;
        
    }
    
    private void addAttachmentToList(Attachment att, Id parentId, List<Attachment> atts)
    {
        if(att != null && att.ParentId == null)
        {
            att.ParentId = parentId;
        }
        if(att != null  && att.Id == null && att.Body != null)
        {
            atts.add(att.clone(false, false, false, false));
            att.Body = null;
        }
    }
    
    private void initAttachments(Id parentId)
    {
        invoiceAttachment = new Attachment(Name='Invoice and Receipt');
        proofAttachment = new Attachment(Name='Proof of Performance');
        attlistAttachment = new Attachment(Name='Attendance List');
        sampleAtachment = new Attachment(Name='Sample Ad');
        eventAttachment = new Attachment(Name='Event Photos');
        addlAttachment1 = new Attachment(Name='Addl1');
        addlAttachment2 = new Attachment(Name='Addl2');
        addlAttachment3 = new Attachment(Name='Addl3');
        if(parentId != null)
        {
            for(Attachment att : [select Id, Body, Name, ParentId from Attachment where ParentId=:parentId])
            {
                if(att.Name == 'Invoice and Receipt')
                {
                    invoiceAttachment = att;
                }
                else if(att.Name == 'Proof of Performance')
                {
                    proofAttachment = att;
                }
                else if(att.Name == 'Attendance List')
                {
                    attlistAttachment = att;
                }
                else if(att.Name == 'Sample Ad')
                {
                    sampleAtachment = att;
                }
                else if(att.Name == 'Event Photos')
                {
                    eventAttachment = att;
                }
                else
                {
                    if(addlAttachment1.Id == null)
                    {
                        addlAttachment1 = att;
                    }
                    else if(addlAttachment2.Id == null)
                    {
                        addlAttachment2 = att;
                    }
                    else if(addlAttachment3.Id == null)
                    {
                        addlAttachment3 = att;
                    }
                }
            }
        }
    }
    
}