objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Approval_Status_Hidden__c</fullName>
        <inlineHelpText>Field for MDF Approval Process</inlineHelpText>
        <label>Approval Status (Hidden)</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchasing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchasing Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Purchasing_Request__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>MDF Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Purchasing_Request__c</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchasing_Request__c.object
<CustomObject>
    <fields>
        <fullName>First_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Chosen approver on web submission</inlineHelpText>
        <label>First Approver</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.PR_Approver__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchasing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchasing Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>PR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchasing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SubmitPurchaseRequestOnMdfApprovalTest.cls
@isTest
public class SubmitPurchaseRequestOnMdfApprovalTest {
    @isTest
    static void testSubmitPurchaseRequestOnMdfApproval()
    {
        List<RecordType> purchaseRecordType = [select Id from RecordType where SobjectType='Purchasing_Request__c' and Name='MDF Request' limit 1];
        Purchasing_Request__c purchase = new Purchasing_Request__c(First_Approver__c = UserInfo.getUserId());
        purchase.RecordTypeId = (purchaseRecordType.size() > 0) ? purchaseRecordType[0].Id : null;
        insert purchase;
        Purchase_Request_Lines__c  prl = new Purchase_Request_Lines__c (Purchasing_Request__c = purchase.Id);
        insert prl;
        
        MDF_Request__c request = new MDF_Request__c(Purchasing_Request__c=purchase.Id);
        insert request;
        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(request.Id);
        Approval.ProcessResult result = Approval.Process(req);
        
        request.Approval_Status_Hidden__c = 'Approved';
        update request;
    }
}