objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Is_Portal_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Portal Request</label>
        <type>Checkbox</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MDFRequestTriggerHandlerForAutoSubmit.cls
/**
 * A Trigger handler of MDF Request.
 * Auto submits a MDF request created from partner portal for approval.
 * 
 *
 * @author  Matt Yuan
 * @created 8/5/2015
 * @version 1.0
 * @since   34.0
 *
 * @changelog
 * 8/5/2015 Matt Yuan - Created.
 */

public class MDFRequestTriggerHandlerForAutoSubmit extends TriggerHandler
{
    public override void afterInsert()
    {
        autoSubmitMDFRequest();
    }

    private void autoSubmitMDFRequest()
    {
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        for(sObject sObj : Trigger.new)
        {
            MDF_Request__c mdfReq = (MDF_Request__c)sObj;
            if(mdfReq.Is_Portal_Request__c)
            {
                Approval.ProcessSubmitRequest submitReq = new Approval.ProcessSubmitRequest();
                submitReq.setComments('Submitting request for approval.');
                submitReq.setObjectId(mdfReq.Id);
                //submitReq.setSubmitterId(UserInfo.getUserId());
                //submitReq.setProcessDefinitionNameOrId('New_MDF_Request');
                //submitReq.setSkipEntryCriteria(true);
                requests.add(submitReq);
            }
        }
        try
        {
            List<Approval.ProcessResult> results = Approval.process(requests, false);
        }
        catch(Exception ex)
        {
            System.debug('An exception was thrown: ' + ex);
        }
    }
}