objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ShareMDFToPartnerTest.cls
@isTest
public class ShareMDFToPartnerTest
{
    @isTest
    static void testMDFShare()
    {
        User portalUser = [select COntactId, COntact.AccountId from User where IsActive = true and UserType = 'PowerPartner' limit 1];
        MDF_Request__c mdf = new MDF_Request__c(Account__c = portalUser.Contact.AccountId);
        MDF_Request__c mdf2 = new MDF_Request__c(Account__c = portalUser.Contact.AccountId);
        insert new List<MDF_Request__c> {mdf, mdf2};
        mdf.Account__c = null;
        update mdf;
        ShareMDFToPartnerHelper.shareMDFs(new List<MDF_Request__c> {mdf, mdf2});
    }
    
    @isTest
    static void testMDFShareSchedule()
    {
        Test.startTest();
        ShareMDFToPartnerSchedule schedulable = new ShareMDFToPartnerSchedule();
        SchedulableContext ctx;
        schedulable.execute(ctx);
        Test.stopTest();
    }
    
    @isTest
    static void testMDFShareBatch()
    {
        Test.startTest();
        String soql = 'select Id, Account__c, OwnerId from MDF_Request__c where Account__c != null limit 1';
        ShareMDFToPartnerBatch currentBatchJob = new ShareMDFToPartnerBatch(soql);
        Database.executeBatch(currentBatchJob, 1);
        Test.stopTest();
    }
}