objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AttachmentCheckOnMDFTest.cls
@isTest
public class AttachmentCheckOnMDFTest {
    @isTest
    public static void test()
    {
    /**
        List<User> portalUsers = [select Id from User where UserType='PowerPartner' and IsActive=true limit 1];
        if(portalUsers.size() > 0)
        {
            System.runas(portalUsers[0])
            {
                MDF_Request__c mdf = new MDF_Request__c(Activity_Complete__c = true);
                insert mdf;
                Attachment att = new Attachment(Name = 'Acme');
                att.Body = Blob.valueOf('abc');
                att.ParentId = mdf.Id;
                try
                {
                    insert att; 
                    System.assert(false, 'There should be an error');
                }catch( Exception ex)
                {
                }
            }
        }
        */
    }
}