objects/Partner_Account_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Partner Account for this Profile</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Resellers</value>
            </filterItems>
            <infoMessage>Can only use reseller account type</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Accounts Profile</relationshipLabel>
        <relationshipName>Partner_Accounts_Profile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LmsDepartmentId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Lms Department Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LmsDepartmentName__c</fullName>
        <label>Lms Department Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner Account Profile</label>
    <nameField>
        <displayFormat>PAP-{0000}</displayFormat>
        <label>Partner Account Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Accounts Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PartnerPortalSSOStubTest.cls
@isTest
private class PartnerPortalSSOStubTest 
{  
    @isTest 
    static void testGetToken() 
    {
        Test.setMock(WebServiceMock.class, new PartnerPortalWebServiceMock());
        String token = PartnerPortalSSOStub.getToken();
        System.assertEquals(token, 'x1x2x3x4x5');
    }
    
    
    @isTest 
    static void testGetSSOLink() 
    {
        Id accountType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Resellers').getRecordTypeId();
        Account portalAccount = new Account(Name = 'TestAccount', RecordTypeId = accountType);
        insert portalAccount;
        insert new Partner_Account_Profile__c(Account__c = portalAccount.Id, LmsDepartmentId__c = '12345');
        
        Contact portalContact = new Contact( FirstName = 'Test', Lastname = 'Amit', AccountId = portalAccount.Id, Email = 'test@test.com');
        insert portalContact;
        Test.startTest();
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = '13g-SP Partner Community' Limit 1];
        User portalUser = new User(
            Username = 'test12345uniquetest@test.com',
            ContactId = portalContact.Id,
            ProfileId = portalProfile.Id,
            Alias = 'test123',
            Email = 'test12345@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Harry',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );
        insert portalUser;
        //portalAccount.OwnerId = portalUser.Id;
        //update portalAccount;
        portalContact.OwnerId = portalUser.Id;
        update portalContact;
        
        System.runAs(portalUser){
            
            //Test.setMock(WebServiceMock.class, new PartnerPortalWebServiceMock());
            Test.setMock(HttpCalloutMock.class, new PartnerPortalApiMock(200, 'OK', 'String body', new Map<String, String> ()));
            try
            {
                String ssoLink = PartnerPortalSSOStub.getSSOLink(UserInfo.getUserId());
            }
            catch(Exception ex) {}
            Test.stopTest();
        }  
    }
    
    @isTest 
    static void testGetSSOLink2() 
    {
        Id accountType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Resellers').getRecordTypeId();
        Account portalAccount = new Account(Name = 'TestAccount', RecordTypeId = accountType);
        insert portalAccount;
        insert new Partner_Account_Profile__c(Account__c = portalAccount.Id, LmsDepartmentName__c = 'Acme');
        
        Contact portalContact = new Contact( FirstName = 'Test', Lastname = 'Amit', AccountId = portalAccount.Id, Email = 'test@test.com');
        insert portalContact;
       
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = '13g-SP Partner Community' Limit 1];
        User portalUser = new User(
            Username = 'test12345unique233test@test.com',
            ContactId = portalContact.Id,
            ProfileId = portalProfile.Id,
            Alias = 'test123',
            Email = 'xxxx@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Harry',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );
        insert portalUser;
        portalContact.OwnerId = portalUser.Id;
        update portalContact;
        
        System.runAs(portalUser){
           Test.startTest();
            Test.setMock(HttpCalloutMock.class, new PartnerPortalApiMock(200, 'OK', 'String body', new Map<String, String> ()));
            try
            {
                String ssoLink = PartnerPortalSSOStub.getSSOLink(UserInfo.getUserId());
            }
            catch(Exception ex) {}
            
            Test.stopTest();
        }  
    }
}