objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Catchall__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Catchall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patch Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patch_Name__c</fullName>
        <description>Name Identifer</description>
        <label>Patch Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Named Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GEO Based</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PatchOverrideController.cls
/*
 * Controller of page PatchOverride
 */
public with sharing class PatchOverrideController 
{
    private sObject obj;
    
    public PatchOverrideController() 
    {
        Id objId = ApexPages.currentPage().getParameters().get('id');
        IsAllowed = true;
        obj = PatchRuleHelper.getSObject(objId);
        ObjectName = (String)obj.get('Name');
        if(obj != null)
        {
            if((Boolean)obj.get('Patch_Locked__c'))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, 'Record is locked, you can\'t override the patch'));
                IsAllowed = false;
            }
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Object is not found'));
        }
    }
    
    public Boolean IsAllowed { get; set; }
    public String CompanyName { get; set; }
    public String EmailDomain { get; set; }
    public String Country { get; set; }
    public String State { get; set; }
    public String ZipCode { get; set; }
    public String Industry { get; set; }
    public String ObjectName { get; set; }
    
    public PageReference reassign()
    {
        PatchRuleEngine.Target target = getPatchTarget();
        try
        {
            Id patchId = PatchRuleEngine.match(target);
            if(patchId == null)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'No match found. Please try with another values.'));
                return null;
            }
            List<Patch__c> patchs = [select Id, Patch_Name__c, Catchall__c, Type__c, Owner__c, Owner__r.GEO__c, RSM__c, CSM__c, SE__c, ISR__c, Active__c from Patch__c where Id=:patchId limit 1];
            if(patchs.size() == 0)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Error occured. Patch Rules need re-deployment'));
                return null;
            }
            PatchRuleHelper.assignPatch(obj, patchs[0]);
            obj.put('Patch_Locked__c', true);
            update obj;
            PatchRuleHelper.willAssignTeamMembers(new List<Id> { obj.Id });
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Patch reassigned.<script>opener.location=\'/'+obj.Id+'\';setTimeout("window.close()", 3000);</script>'));
        }
        catch(Exception ex)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Failed to reassign, the error message is: ' + ex.getMessage()));
        }
        return null;
    }
    
    private PatchRuleEngine.Target getPatchTarget()
    {
        PatchRuleEngine.Target target = new PatchRuleEngine.Target();
        target.Company = CompanyName;
        target.EmailDomain = PatchRuleHelper.getEmailDomain(EmailDomain);
        target.Country = Country;
        target.ZipCode = ZipCode;
        target.State = State;
        target.Industry = Industry;
        return target;
    }
}