objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patch_Name__c</fullName>
        <description>Name Identifer</description>
        <label>Patch Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessingSequence__c</fullName>
        <inlineHelpText>Smaller number gets higher priority</inlineHelpText>
        <label>Processing Sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PatchUserReplaceControllerTest.cls
@isTest
public class PatchUserReplaceControllerTest
{
    @isTest
    static void test()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', Active__c=true, RSM__c=UserInfo.getUserId(), ProcessingSequence__c=1);
        insert patch;
        
        PageReference ref = new PageReference('/apex/PatchUserReplace?uid=' + UserInfo.getUserId() + '&pid=' + patch.Id);
        Test.setCurrentPage(ref);
        PatchUserReplaceController controller = new PatchUserReplaceController();
        List<SelectOption> patches = controller.Patches;
        System.assertEquals(2, patches.size());
        controller.save();
    }
}