objects/Purchasing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Send_PO_to_Vendor__c</fullName>
        <label>Send PO to Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Temporary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true or false</description>
        <label>Temporary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <label>Vendor Name</label>
        <length>175</length>
        <type>Text</type>
    </fields>
    <label>Purchasing Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>PR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchasing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PurchaseRequestControllerTest.cls
@isTest
public class PurchaseRequestControllerTest
{
    @isTest
    public static void testController()
    {
        Purchasing_Request__c request = new Purchasing_Request__c(Vendor_Name__c = 'acme',Temporary__c = true, Send_PO_to_Vendor__c='NO');
        PageReference refer = new PageReference('/apex/PurchaseRequest');
        Test.setCurrentPage(refer);
        PurchaseRequestController controller = new PurchaseRequestController(new ApexPages.StandardController(request));
        controller.init();
        List<Purchase_Request_Lines__c> lines = controller.getLines();
        controller.getApprovers();
        
        lines[0].Qty__c = 1;
        lines[1].Qty__c = 2;

        controller.addLine();
        
        PageReference page = new PageReference('/apex/PurchaseRequest?index=2');
        Test.setCurrentPage(page);
        controller.removeLine();
        
        controller.request.Vendor_Name__c= 'acme';
        controller.attach.Name = 'acme';
        controller.attach.Body = Blob.valueOf('acme');
        controller.saveFile();
        
        controller.save();
        
        String[] attachments = controller.FileNames;
        System.assertEquals(1, attachments.size());
        System.assert(controller.request.Id != null);
 
        controller.formReset();
    }
}