objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>PreparedFor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prepared For</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{00000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteEmailReviewHelper.cls
public class QuoteEmailReviewHelper {
    
    public static void SendEmailForECApproval(Quote__c quoteDtl)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //mail.setTargetObjectId(quoteDtl.PreparedFor__c);
        mail.setSubject('Edge Connect Quote '+quoteDtl.Name+ ' for review.');
        string Url = System.URL.getSalesforceBaseUrl().toExternalForm()+'/'+quoteDtl.Id;
        mail.setPlainTextBody('This quote has Edge connect products and needs your review.'+
                              'Once the review is complete, please check the EC Approval on the quote.'+
                              'Please find the link: '+ Url );
        mail.setSaveAsActivity(false);           
        mail.setToAddresses(new String[] {'SalesOps@Silver-Peak.com'});
        mail.setUseSignature(false);
      
        Messaging.sendEmail(new Messaging.Email[] {mail});
    }
    
    
    public static boolean IsECApprovalRequired(Quote__c quoteDtl)
        {
        List<Quote_Line__c> quotedtls=null;
        if(quoteDtl!=null)
        {
            quotedtls= [Select Id, Product__r.Name from Quote_Line__c where Quote__c=:quoteDtl.Id and Product__r.Name like 'EC%' ];
        }
        if(quotedtls!=null && quotedtls.size()>0)
        {
            return true;
        }
        return false;
    }
    
    
}