objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cond PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller Demo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quote_Date__c</fullName>
        <description>Quote Date</description>
        <label>Quote Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_Valid_Until__c</fullName>
        <description>Quote Valid Until</description>
        <label>Quote Valid Until</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Percent</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>11</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{00000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OppoQuoteController.cls
public class OppoQuoteController
{
    public Enum CopyStage{CopyAndEdit, CopyOnly, DoNotCopy}
    public Opportunity oppo{get;set;}
    public Quote__c quote{get;set;}
    public Integer stage{get;set;}
    
    public OppoQuoteController(ApexPages.StandardController controller)
    {
        String oppoId = ((Opportunity)controller.getRecord()).Id;
        if(oppoId instanceOf Id)
        {
            oppo = [select name, account.name, Pricebook2Id, HasOpportunityLineItem, 
                       (Select Id From OpportunityLineItems)
                    from opportunity where id = :oppoId];
            //oppo = new Opportunity();
            quote = new Quote__c(Opportunity__r = oppo, Opportunity__c = oppoId, Quote_Date__c = Date.today(), PaymentTerm__c = 'Net 30', Quote_Valid_Until__c = Date.today().addDays(30));
        }
        else
        {
            quote = new Quote__c();
        }
    }
    
    public List<SelectOption> getPriceBooks()
    {
        List<SelectOption> options = new List<SelectOption>();
        for(Pricebook2 book : [select Id, Name from Pricebook2])
        {
            options.add(new SelectOption(book.Id, book.Name));
        }
        return options;
    }
    
    public void copyItemsToQuote()
    {
        OpportunityLineItem[] olist;
        
        olist = [select Id, OpportunityId, SortOrder, PricebookEntryId, Quantity, 
                    TotalPrice, UnitPrice, ListPrice, DiscountPercent__c, ServiceDate, Description, CreatedDate, 
                    CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                    IsDeleted , PricebookEntry.Name, PricebookEntry.Product2id
                    From OpportunityLineItem 
                    where OpportunityId = :quote.Opportunity__c ];
        
        // create new quote lines
        Quote_Line__c[] qlines = new list<Quote_Line__c>(); 
        for ( OpportunityLineItem oitem : olist) 
        {
            Quote_Line__c ql = new Quote_Line__c(
                                                    Quote__c = quote.id,
                                                    Discount_Percent__c = oitem.DiscountPercent__c,
                                                    Quantity__c = oitem.Quantity,
                                                    Unit_Price__c = oitem.UnitPrice,
                                                    //Description__c = oitem.Description,
                                                    //ServiceDate__c = oitem.ServiceDate,
                                                    Product__c = oitem.PricebookEntry.Product2id
                                                ); 
            qlines.add(ql);     
        }
        if ( qlines.size() > 0 ) 
        {
            delete [select Id from Quote_Line__c where Quote__c = :quote.id];
            insert qlines;
        }
    }
    
    public PageReference cancel()
    {
        return new PageReference('/' + oppo.Id);
    }
    
    public PageReference save()
    {
        SavePoint sp = Database.setSavePoint();
        try
        {
            PageReference returnPage;
            if(!oppo.HasOpportunityLineItem)
            {
                update oppo;
                upsert quote;
                returnPage = new PageReference('/apex/LookupProducts?id=' + quote.Id);
            }
            else
            {
                upsert quote;
                if(stage == CopyStage.CopyAndEdit.ordinal())
                {
                    copyItemsToQuote(); 
                    returnPage = new PageReference('/apex/editQuoteLines?id=' + quote.Id);                   
                }
                else
                {
                    returnPage = new PageReference('/' + quote.Id);
                    if(stage == CopyStage.CopyOnly.ordinal())
                    {
                        copyItemsToQuote();                         
                    }
                    else
                    if(stage == CopyStage.DoNotCopy.ordinal())
                    {
                        //do noting right now
                    } 
                }             
            }
            return returnPage;           
        }
        catch(exception ex)
        {
            Database.rollback(sp);
            ApexPages.addMessages(ex);
            return null;
        }
    }
}