objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{00000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EditQuoteLinesRedirectController.cls
/*
 * extension class of visualforce page EditQuoteLinesRedirect
 * just redirects the standard edit and del button of Quote_Line to the desired page EditQuoteLine
 */
public class EditQuoteLinesRedirectController 
{
	private String quoteId;
	public EditQuoteLinesRedirectController(ApexPages.StandardController controller)
	{
		Quote_Line__c record = (Quote_Line__c)controller.getRecord();
		if(record != null)
		{
			quoteId = record.Quote__c;
		}
	}
	
	public PageReference redirect()
	{
		return new PageReference('/apex/EditQuoteLines?id=' + quoteId);
	}
	
	@isTest
	static void testEditQuoteLinesRedirectController()
	{
		List<Quote_Line__c> lines = [select Id, Quote__c from Quote_Line__c limit 1];
		if(lines.size() > 0)
		{
			EditQuoteLinesRedirectController controller = new EditQuoteLinesRedirectController(new ApexPages.StandardController(lines[0]));
			System.assert(controller.redirect() != null);
		}
	}
}