objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>Approval_Made__c</fullName>
        <defaultValue>false</defaultValue>
        <description>check this box in the approval stage and then only uncheck it if the discount percentage changes again</description>
        <label>Approval Made</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <description>Formula for Quote Approval Matrix - 06-12-10: IF(or( 
AND( 
OR( 
and(Discount_Max__c &gt; 0.35, Discount_Max__c &gt; RegPartProdDisc__c ), 
Average_Discount__c &gt; 0.0, 
and( Service_Discount_Max__c &gt; 0.15, Service_Discount_Max__c &gt; RegPartServDisc__c )), 
Approval_Made__c =FALSE), OR(and(ConsultingDiscountMax__c &gt;0,Opportunity__r.Account.IsAPartner__c =0) ,AND(ConsultingDiscountMax__c &gt;0.50, Opportunity__r.Account.IsAPartner__c =1))), 
1, 0)
Updated for tiering 6-24-2010
IF(or( 
AND( 
OR( 
and(Discount_Max__c &gt; 0.35, Discount_Max__c &gt; RegPartProdDisc__c ), 
Average_Discount__c &gt; 0.0, 
and( OR( and(Service_Discount_Max__c &gt; 0.21, MultiYearValue__c =2), and(Service_Discount_Max__c &gt; 0.27, MultiYearValue__c =3), Service_Discount_Max__c &gt; 0.15), Service_Discount_Max__c &gt; RegPartServDisc__c )), 
Approval_Made__c =FALSE), OR(and(ConsultingDiscountMax__c &gt;0,Opportunity__r.Account.IsAPartner__c =0) ,AND(ConsultingDiscountMax__c &gt;0.50, Opportunity__r.Account.IsAPartner__c =1))), 
1, 0)</description>
        <formula>IF(OR( 
AND( OR( AND( ApprovalLevelMax__c &gt;0, Discount_Max__c &gt; RegPartProdDisc__c  ),  Level3Required__c =1,
and(Service_Discount_Max__c &gt; 0.24, MultiYearValue__c =2,Service_Discount_Max__c &gt; RegPartServDisc__c), 
and(Service_Discount_Max__c &gt; 0.27, MultiYearValue__c =3,Service_Discount_Max__c &gt; RegPartServDisc__c), 
AND(and(Service_Discount_Max__c &gt; 0.20,MultiYearValue__c &lt;2) , Service_Discount_Max__c &gt; RegPartServDisc__c)) 
, NOT(Approval_Made__c )), 
OR(and(ConsultingDiscountMax__c &gt;1,Opportunity__r.Account.IsAPartner__c =0) , 
AND(ConsultingDiscountMax__c &gt;1, Opportunity__r.Account.IsAPartner__c =1) ) 
, Opportunity__r.Primary_Partner__r.CreditHold__c, 
AND(ISPICKVAL(Opportunity__r.Type,&apos;Training/WanStart&apos;), ConsultingDiscountMax__c &gt; RegPartServDisc__c ) ) 
,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConsultingDiscountMax__c</fullName>
        <label>Consulting Discount Max</label>
        <summarizedField>Quote_Line__c.Discount_Percent__c</summarizedField>
        <summaryFilterItems>
            <field>Quote_Line__c.Include4ConsultingDisc__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>Quote_Line__c.Quote__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>EC_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EC Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MultiYearValue__c</fullName>
        <description>What is the maximum multi year value</description>
        <label>MultiYearValue</label>
        <summarizedField>Quote_Line__c.Include4MultiYYear__c</summarizedField>
        <summaryFilterItems>
            <field>Quote_Line__c.Include4MultiYYear__c</field>
            <operation>greaterThan</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>Quote_Line__c.Quote__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreparedFor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prepared For</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Date__c</fullName>
        <description>Quote Date</description>
        <label>Quote Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_Valid_Until__c</fullName>
        <description>Quote Valid Until</description>
        <label>Quote Valid Until</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegPartServDisc__c</fullName>
        <formula>Max( Opportunity__r.Registered_Partner__r.Registered_Discount_Service__c ,
 Opportunity__r.Registered_Partner__r.Standard_Discount_Service__c,
 Opportunity__r.Primary_Partner__r.Registered_Discount_Service__c ,
 Opportunity__r.Primary_Partner__r.Standard_Discount_Service__c,
 Opportunity__r.Account.Maintenance_Discount__c   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>this is maximum discount available without requiring approval for a quote on a given opportunity. It is the greater of the primary partner negotiated discount rates or the customer negotiated discount rates.</inlineHelpText>
        <label>Partner Service Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Discount_Max__c</fullName>
        <label>Service Discount Max</label>
        <summarizedField>Quote_Line__c.Discount_Percent__c</summarizedField>
        <summaryFilterItems>
            <field>Quote_Line__c.Include4ServiceDiscount__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>Quote_Line__c.Quote__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Percent</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>11</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{00000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestQuoteEmailReviewHelper.cls
@IsTest
public class TestQuoteEmailReviewHelper {
  
    public static void TestECApprovalRequired()
    {
        //Initial test parameters.
        //create opportunity, product, priceboock, pricebookentry, opportunitylineitem 
        Product2 prod = new product2(name='EC-x', Product_Category__c = 'Subscription', isActive = true, isQuotable__c = true);
        insert prod;
        Product2 prod2 = new product2(name='EC-y', Product_Category__c = 'Subscription', isActive = true, isQuotable__c = true);
        insert prod2;
        Pricebook2 stdPb = [select Id from Pricebook2 where IsStandard=true limit 1];
        insert new PricebookEntry(pricebook2id = stdPb.id, product2id = prod.id, unitprice=1.0, isActive=true);
        insert new PricebookEntry(pricebook2id = stdPb.id, product2id = prod2.id, unitprice=2.0, isActive=true);
        //creates a new pricebook with an entry for this product
        Pricebook2 book = new Pricebook2(name='test');
        insert book;
        PricebookEntry entry = new PricebookEntry(pricebook2id=book.id, product2id=prod.id, unitprice=1.0, isActive=true);
        insert entry;
        insert new PricebookEntry(pricebook2id=book.id, product2id=prod2.id, unitprice=1.0, isActive=true);
        
        Account account = new Account(Name = 'acme');
        account.Registered_Discount_EdgeConnect__c= 30;
        account.Registered_Discount_Product__c= 30;
        account.Registered_Discount_Service__c= 30;
        account.Standard_Discount_EdgeConnect__c= 30;
        account.Standard_Discount_Product__c= 30;
        account.Standard_Discount_Service__c= 30;
        account.Partner_Discount__c= 30;
        insert account;
        //create opportunity and opportunity line item.
        Opportunity oppo = new Opportunity(name='test',AccountId=account.id, pricebook2id=book.id, stageName='Discovery', CloseDate=Date.newInstance(2006,10,10));
        insert oppo;
        OpportunityLineItem oli = new OpportunityLineItem(opportunityid=oppo.id, pricebookentryid=entry.id, unitprice=1.5, quantity=2);
        insert oli;
        Quote__c qt = new Quote__c(Opportunity__c = oppo.Id, Quote_Valid_Until__c = Date.today(), Quote_Date__c = Date.today());
        insert qt;     
        
        Test.startTest();
        //test constructor
        QuoteController controller = new QuoteController(new ApexPages.StandardController(qt));
        System.debug('controller exists');
        PageReference refer = new PageReference('/apex/EditQuoteLines');
        Test.setCurrentPage(refer);

        //copy line items from opportunity to quote
        ApexPages.currentPage().getParameters().put('reloadQuote', '1');
        controller.copy();
        System.assert([Select count() from Quote_Line__c where Quote__c = :qt.Id] == 1);
        ApexPages.currentPage().getParameters().remove('reloadQuote');
        
        //reload controller since copy line items from opportunity refreshs the quote's child records.
        controller = new QuoteController(new ApexPages.StandardController(qt));
        System.debug(controller.items.size());
        controller.getProductGroups();
        //search all products
        controller.add();
        controller.searchKeyword = '';
        controller.getFilterValues();
        controller.filterValue = 'all';
        controller.search();  
        System.debug(controller.searchResults);
        System.debug(controller.items.size());
        System.assert(controller.searchResults.size() >= 2);
        
        //search and add products
        controller.add();
        controller.filterValue = 'Subscription';
        controller.search();
        controller.selectedProds = controller.searchResults[0].Id + ';' + controller.searchResults[1].Id + ';' ;
        controller.addProducts();
        controller.getPricebooks();
        controller.add();
        controller.reset();
        
        controller.add();
        controller.filterValue = 'Subscription';
        controller.search();
        controller.selectedProds = controller.searchResults[0].Id + ';' + controller.searchResults[1].Id + ';' ;
        controller.addProducts();
        Quote_Line__c line = controller.items[1].record;
        line.Quantity__c = 2;
        line.Discount_Percent__c = 10;        
        String cf = controller.CurrencyFormat;
        String qd = controller.QuoteDate;
        String vu = controller.validUntil;
        String ta = controller.totalAmount;
        Boolean sa = controller.showVirtualAlternative;
        Quote__c q = controller.getQuote();
        List<QuoteController.LineItem> its = controller.getItems();
        Quote_Line__c line2 = controller.items[2].record;
        line2.Quantity__c = 2;
        line2.Discount_Percent__c = 10; 

        System.assert(controller.items.size() == 3);     
        controller.asyncUpdatePrice();
        
        //delete the first line
        ApexPages.currentPage().getParameters().put('delIndex', '0');
        controller.del();
        //calculate discount by price
        controller.items[1].record.Unit_Price__c = 0.75;
        controller.asyncUpdateProduct();
                       
        controller.save();       
        Quote__c finalQuote= [Select ConsultingDiscountMax__c,Opportunity__r.Account.IsAPartner__c,Opportunity__r.Primary_Partner__r.CreditHold__c,Opportunity__r.Type, Id,Name,EC_Approval__c,PreparedFor__c,PreparedFor__r.Email,Approval_Required__c,Approval_Made__c,Service_Discount_Max__c,RegPartServDisc__c ,MultiYearValue__c  from Quote__c where Id=:q.Id ];
        System.assertEquals(true,QuoteEmailReviewHelper.IsECApprovalRequired(finalQuote));
        
        Test.stopTest();
    }
    
   
    public static void TestECApprovalNotRequired()
    {
        //Initial test parameters.
        //create opportunity, product, priceboock, pricebookentry, opportunitylineitem 
        Product2 prod = new product2(name='VX-x', Product_Category__c = 'Subscription', isActive = true, isQuotable__c = true);
        insert prod;
        Product2 prod2 = new product2(name='VX-y', Product_Category__c = 'Subscription', isActive = true, isQuotable__c = true);
        insert prod2;
        Pricebook2 stdPb = [select Id from Pricebook2 where IsStandard=true limit 1];
        insert new PricebookEntry(pricebook2id = stdPb.id, product2id = prod.id, unitprice=1.0, isActive=true);
        insert new PricebookEntry(pricebook2id = stdPb.id, product2id = prod2.id, unitprice=2.0, isActive=true);
        //creates a new pricebook with an entry for this product
        Pricebook2 book = new Pricebook2(name='test');
        insert book;
        PricebookEntry entry = new PricebookEntry(pricebook2id=book.id, product2id=prod.id, unitprice=1.0, isActive=true);
        insert entry;
        insert new PricebookEntry(pricebook2id=book.id, product2id=prod2.id, unitprice=1.0, isActive=true);
        
        Account account = new Account(Name = 'acme');
        account.Registered_Discount_EdgeConnect__c= 30;
        account.Registered_Discount_Product__c= 30;
        account.Registered_Discount_Service__c= 30;
        account.Standard_Discount_EdgeConnect__c= 30;
        account.Standard_Discount_Product__c= 30;
        account.Standard_Discount_Service__c= 30;
        account.Partner_Discount__c= 30;
        insert account;
        //create opportunity and opportunity line item.
        Opportunity oppo = new Opportunity(name='test',AccountId=account.id, pricebook2id=book.id, stageName='Discovery', CloseDate=Date.newInstance(2006,10,10));
        insert oppo;
        OpportunityLineItem oli = new OpportunityLineItem(opportunityid=oppo.id, pricebookentryid=entry.id, unitprice=1.5, quantity=2);
        insert oli;
        Quote__c qt = new Quote__c(Opportunity__c = oppo.Id, Quote_Valid_Until__c = Date.today(), Quote_Date__c = Date.today());
        insert qt;     
        
        Test.startTest();
        //test constructor
        QuoteController controller = new QuoteController(new ApexPages.StandardController(qt));
        System.debug('controller exists');
        PageReference refer = new PageReference('/apex/EditQuoteLines');
        Test.setCurrentPage(refer);

        //copy line items from opportunity to quote
        ApexPages.currentPage().getParameters().put('reloadQuote', '1');
        controller.copy();
        System.assert([Select count() from Quote_Line__c where Quote__c = :qt.Id] == 1);
        ApexPages.currentPage().getParameters().remove('reloadQuote');
        
        //reload controller since copy line items from opportunity refreshs the quote's child records.
        controller = new QuoteController(new ApexPages.StandardController(qt));
        System.debug(controller.items.size());
        controller.getProductGroups();
        //search all products
        controller.add();
        controller.searchKeyword = '';
        controller.getFilterValues();
        controller.filterValue = 'all';
        controller.search();  
        System.debug(controller.searchResults);
        System.debug(controller.items.size());
        System.assert(controller.searchResults.size() >= 2);
        
        //search and add products
        controller.add();
        controller.filterValue = 'Subscription';
        controller.search();
        controller.selectedProds = controller.searchResults[0].Id + ';' + controller.searchResults[1].Id + ';' ;
        controller.addProducts();
        controller.getPricebooks();
        controller.add();
        controller.reset();
        
        controller.add();
        controller.filterValue = 'Subscription';
        controller.search();
        controller.selectedProds = controller.searchResults[0].Id + ';' + controller.searchResults[1].Id + ';' ;
        controller.addProducts();
        Quote_Line__c line = controller.items[1].record;
        line.Quantity__c = 2;
        line.Discount_Percent__c = 10;        
        String cf = controller.CurrencyFormat;
        String qd = controller.QuoteDate;
        String vu = controller.validUntil;
        String ta = controller.totalAmount;
        Boolean sa = controller.showVirtualAlternative;
        Quote__c q = controller.getQuote();
        List<QuoteController.LineItem> its = controller.getItems();
        Quote_Line__c line2 = controller.items[2].record;
        line2.Quantity__c = 2;
        line2.Discount_Percent__c = 10; 

        System.assert(controller.items.size() == 3);     
        controller.asyncUpdatePrice();
        
        //delete the first line
        ApexPages.currentPage().getParameters().put('delIndex', '0');
        controller.del();
        //calculate discount by price
        controller.items[1].record.Unit_Price__c = 0.75;
        controller.asyncUpdateProduct();
                       
        controller.save();       
        Quote__c finalQuote= [Select ConsultingDiscountMax__c,Opportunity__r.Account.IsAPartner__c,Opportunity__r.Primary_Partner__r.CreditHold__c,Opportunity__r.Type, Id,Name,EC_Approval__c,PreparedFor__c,PreparedFor__r.Email,Approval_Required__c,Approval_Made__c,Service_Discount_Max__c,RegPartServDisc__c ,MultiYearValue__c  from Quote__c where Id=:q.Id ];
        System.assertEquals(false,QuoteEmailReviewHelper.IsECApprovalRequired(finalQuote));
        
        Test.stopTest();
    }    
}