objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>Approval_Made__c</fullName>
        <defaultValue>false</defaultValue>
        <description>check this box in the approval stage and then only uncheck it if the discount percentage changes again</description>
        <label>Approval Made</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <description>Formula for Quote Approval Matrix - 06-12-10: IF(or( 
AND( 
OR( 
and(Discount_Max__c &gt; 0.35, Discount_Max__c &gt; RegPartProdDisc__c ), 
Average_Discount__c &gt; 0.0, 
and( Service_Discount_Max__c &gt; 0.15, Service_Discount_Max__c &gt; RegPartServDisc__c )), 
Approval_Made__c =FALSE), OR(and(ConsultingDiscountMax__c &gt;0,Opportunity__r.Account.IsAPartner__c =0) ,AND(ConsultingDiscountMax__c &gt;0.50, Opportunity__r.Account.IsAPartner__c =1))), 
1, 0)
Updated for tiering 6-24-2010
IF(or( 
AND( 
OR( 
and(Discount_Max__c &gt; 0.35, Discount_Max__c &gt; RegPartProdDisc__c ), 
Average_Discount__c &gt; 0.0, 
and( OR( and(Service_Discount_Max__c &gt; 0.21, MultiYearValue__c =2), and(Service_Discount_Max__c &gt; 0.27, MultiYearValue__c =3), Service_Discount_Max__c &gt; 0.15), Service_Discount_Max__c &gt; RegPartServDisc__c )), 
Approval_Made__c =FALSE), OR(and(ConsultingDiscountMax__c &gt;0,Opportunity__r.Account.IsAPartner__c =0) ,AND(ConsultingDiscountMax__c &gt;0.50, Opportunity__r.Account.IsAPartner__c =1))), 
1, 0)</description>
        <formula>IF(OR( 
AND( OR( AND( ApprovalLevelMax__c &gt;0, Discount_Max__c &gt; RegPartProdDisc__c  ),  Level3Required__c =1,
and(Service_Discount_Max__c &gt; 0.24, MultiYearValue__c =2,Service_Discount_Max__c &gt; RegPartServDisc__c), 
and(Service_Discount_Max__c &gt; 0.27, MultiYearValue__c =3,Service_Discount_Max__c &gt; RegPartServDisc__c), 
AND(and(Service_Discount_Max__c &gt; 0.20,MultiYearValue__c &lt;2) , Service_Discount_Max__c &gt; RegPartServDisc__c)) 
, NOT(Approval_Made__c )), 
OR(and(ConsultingDiscountMax__c &gt;1,Opportunity__r.Account.IsAPartner__c =0) , 
AND(ConsultingDiscountMax__c &gt;1, Opportunity__r.Account.IsAPartner__c =1) ) 
, Opportunity__r.Primary_Partner__r.CreditHold__c, 
AND(ISPICKVAL(Opportunity__r.Type,&apos;Training/WanStart&apos;), ConsultingDiscountMax__c &gt; RegPartServDisc__c ) ) 
,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EC Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreparedFor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prepared For</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EmailQuoteDocumentController.cls
/*
* Controller of page EmailQuoteDocument
*/
public with sharing class EmailQuoteDocumentController 
{
    private Quote__c quote;
    
    public EmailQuoteDocumentController(ApexPages.StandardController controller) 
    {
        quote = (Quote__c)controller.getRecord();
        //ECApprovalRequired=false;
        ccAddr = UserInfo.getUserEmail();
        subject = 'Quote for ' + quote.Opportunity__r.Account.Name;
       
    }
    /*
    public PageReference SendForReview()
    {
        Quote__c quoteDtl=[Select Id,Name,EC_Approval__c,PreparedFor__c,PreparedFor__r.Email,Approval_Required__c,Approval_Made__c from Quote__c where Id=:quote.Id ];
        if(quoteDtl!=null && !quoteDtl.EC_Approval__c  && !quoteDtl.Approval_Made__c  && QuoteEmailReviewHelper.IsECApprovalRequired(quoteDtl))
        {
            if(quoteDtl.Approval_Required__c==0)
            {
                ECApprovalRequired=true;
                SendEmailForECApproval(quoteDtl);
            }
        }
     
        return null;
    }*/
    public String ccAddr { get; set; }
    //public boolean ECApprovalRequired { get; set; }
    public String OutputMessage { get; set; }
    public String subject { get; set; }
    public String body { get; set; }
    
    /*
    private void SendEmailForECApproval(Quote__c quoteDtl)
    {
        try
        {
            QuoteEmailReviewHelper.SendEmailForECApproval(quoteDtl);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'An email has been sent to "Sales Operations" for EC Approval review. <script>setTimeout("top.close()", 3000)</script>'));
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }*/
    public PageReference send()
    {
        Messaging.SingleemailMessage email = new Messaging.SingleEmailMessage();
        email.setTargetObjectId(quote.PreparedFor__c);
        if(ccAddr != null)
        {
            String[] addresses = ccAddr.split('[,;]');
            if(addresses.size() > 0)
            {
                email.setCcAddresses(addresses);
            }
        }
        email.setSubject(subject);
        email.setPlainTextBody(body);
        try
        {
            PageReference downloadPdf = new PageReference('/apex/quotepdf?id='+quote.Id);
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setBody(downloadPdf.getContent());
            attachment.setContentType('application/pdf');
            String attachmentName = (quote.Opportunity__r.Account.Name == null) ? 'Quote.pdf' : 'Quote for ' + quote.Opportunity__r.Account.Name + '.pdf';
            attachment.setFilename(attachmentName);
            email.setFileAttachments(new List<Messaging.EmailFileAttachment> {attachment});
            Messaging.sendEmail(new List<Messaging.Email> { email });
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'An email was sent. <script>setTimeout("top.close()", 3000)</script>'));
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
        }
        return null;
    }
}