objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingStreet ,  PreparedFor__r.Account.BillingStreet )</description>
        <formula>if(  Override_Bill_To__c ,  Billing_Address__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingStreet ,  PreparedFor__r.Account.BillingStreet ))</formula>
        <label>Bill To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingCity ,  PreparedFor__r.Account.BillingCity )</description>
        <formula>if(  Override_Bill_To__c ,  Billing_City__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingCity ,  PreparedFor__r.Account.BillingCity ))</formula>
        <label>Bill To City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingCountry ,  PreparedFor__r.Account.BillingCountry )</description>
        <formula>if(  Override_Bill_To__c ,  Billing_Country__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingCountry ,  PreparedFor__r.Account.BillingCountry ))</formula>
        <label>Bill To Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingState ,  PreparedFor__r.Account.BillingState )</description>
        <formula>if(  Override_Bill_To__c ,  Billing_State__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingState ,  PreparedFor__r.Account.BillingState ))</formula>
        <label>Bill To State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Zip__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingPostalCode ,  PreparedFor__r.Account.BillingPostalCode )</description>
        <formula>if(  Override_Bill_To__c ,  Billing_Postal_Code__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.BillingPostalCode ,  PreparedFor__r.Account.BillingPostalCode ))</formula>
        <label>Bill To Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentTermInstructions__c</fullName>
        <label>Payment Term Instructions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cond PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller Demo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreparedFor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prepared For</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Amount_Rollup__c</fullName>
        <label>Quote Amount Rollup</label>
        <summarizedField>Quote_Line__c.Line_Price__c</summarizedField>
        <summaryForeignKey>Quote_Line__c.Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Quote_Date__c</fullName>
        <description>Quote Date</description>
        <label>Quote Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_Discount_Percent__c</fullName>
        <label>Quote Discount Percent</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quote_Valid_Until__c</fullName>
        <description>Quote Valid Until</description>
        <label>Quote Valid Until</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingStreet ,  PreparedFor__r.Account.ShippingStreet )</description>
        <formula>if(  Override_Ship_To__c , Shipping_Address__c ,IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingStreet ,  PreparedFor__r.Account.ShippingStreet ))</formula>
        <label>Ship To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingCity ,  PreparedFor__r.Account.ShippingCity )</description>
        <formula>if(  Override_Ship_To__c , Shipping_City__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingCity ,  PreparedFor__r.Account.ShippingCity ))</formula>
        <label>Ship To City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingCountry ,  PreparedFor__r.Account.ShippingCountry )</description>
        <formula>if(  Override_Ship_To__c ,  Shipping_Country__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingCountry ,  PreparedFor__r.Account.ShippingCountry ))</formula>
        <label>Ship To Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingState ,  PreparedFor__r.Account.ShippingState )</description>
        <formula>if(  Override_Ship_To__c ,  Shipping_State__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingState ,  PreparedFor__r.Account.ShippingState ))</formula>
        <label>Ship To State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Zip__c</fullName>
        <description>IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingPostalCode ,  PreparedFor__r.Account.ShippingPostalCode )</description>
        <formula>if(  Override_Ship_To__c ,  Shipping_Postal_Code__c , IF( ISPICKVAL( Quote_Address__c ,&quot;Opportunity Account&quot;) ,Opportunity__r.Account.ShippingPostalCode ,  PreparedFor__r.Account.ShippingPostalCode ))</formula>
        <label>Ship To Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowDiscount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <defaultValue>&quot;Pricing shown is transfer prices from Silver Peak to Reseller, NOT End-user pricing.&quot;</defaultValue>
        <label>Special Instructions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Percent</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Line_Price__c</fullName>
        <formula>Quantity__c  *  Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>11</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{00000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteEmailController.cls
public class QuoteEmailController
{
    class QuoteLine
    {
        public PricebookEntry price{get;set;} 
        public Quote_Line__c record{get;set;}
    }
    public Opportunity getOppo() 
    {
        List<Opportunity> oppos = [select name, account.name, account.phone, Owner.Phone, Owner.Email, Owner.Name, 
                    (Select Id From OpportunityLineItems)
                    from opportunity where id = :quote.opportunity__c limit 1];
                    //Account.ShippingCountry, Account.ShippingPostalCode, Account.ShippingState, Account.ShippingCity, Account.ShippingStreet, 
                    //Account.BillingCountry, Account.BillingPostalCode, Account.BillingState, Account.BillingCity, Account.BillingStreet, 
        if(oppos != null && oppos.size() > 0)
        {
            return oppos[0];
        }
        return null;
    }

    private List<QuoteLine> lines;
    public List<QuoteLine> getLines()
    {
        lines = new List<QuoteLine>();
        List<Quote_Line__c> quoteLines = [Select Id, Name, Quantity__c, Product__c, Discount_Percent__c, Unit_Price__c, Line_Price__c, Product__r.Name, product__r.productCode, product__r.description, Product__r.Product_Category__c From Quote_Line__c where Quote__c = :quote.Id order by Product__r.Product_Category__c, product__r.productCode]; 
        List<PricebookEntry> entries = [Select UnitPrice, Product2Id From PricebookEntry where Pricebook2Id = :quote.Opportunity__r.Pricebook2Id];
        for(Quote_Line__c quoteLine : quoteLines)
        {
            QuoteLine line = new QuoteLine();
            line.record = quoteLine;
            for(PricebookEntry entry : entries)
            {
                if(entry.Product2Id == quoteLine.Product__c)
                {
                    line.price = entry;
                    break;
                }                
            }
            lines.add(line);
        }
        return lines;
    }

    public Quote__c quote
    {
        get
        {
            List<Quote__c> quotes = [Select Opportunity__r.Name, Opportunity__r.Description, Lastmodifieddate, Opportunity__r.Pricebook2Id, Opportunity__r.StageName, Stage__c, 
                    Quote_Valid_Until__c, Quote_Discount_Percent__c, Quote_Date__c, PreparedFor__c, PreparedFor__r.Name, PreparedFor__r.Phone,
                    Quote_Amount_Rollup__c, Primary__c, Opportunity__c, Name, Id, PaymentTerm__c, Special_Instructions__c, ShowDiscount__c, PaymentTermInstructions__c,
                    Bill_To_Address__c, Bill_To_City__c, Bill_To_State__c, Bill_To_Zip__c, Bill_To_Country__c,
                    Ship_To_Address__c, Ship_To_City__c, Ship_To_State__c, Ship_To_Zip__c, Ship_To_Country__c,
                    (Select Id, Name, Quote__c, Product__c, Quantity__c, Discount_Percent__c, Unit_Price__c, 
                        Line_Price__c, Product__r.Name, product__r.productCode, product__r.description, Product__r.Product_Category__c 
                        From Quote_Lines__r order by Product__r.Product_Category__c, product__r.productCode) 
                    From Quote__c where Id = :quote.Id limit 1];
            if(quotes != null && quotes.size() > 0)
            {
                quote = quotes[0];
            }
            return quote;

        }
        set;
    }
    
    public QuoteEmailController()
    {
        quote = new Quote__c();
    }
    
    @isTest
    static void test()
    {
        QuoteEmailController controller = new QuoteEmailController();
        Quote__c quote = controller.quote;
        List<QuoteLine> lines = controller.getLines();
        Opportunity opp = controller.getOppo();
    }
}