objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestOpportunityPocStatusBatchJob.cls
@isTest
public class TestOpportunityPocStatusBatchJob {
	@isTest
    public  static void test()
    {
        Account acct = new Account(Name = 'Acme');
        insert acct;
        Opportunity opp = new Opportunity(Name='test', StageName='Discovery', CloseDate=Date.newInstance(2006,10,10),AccountId = acct.Id);
        insert opp;
        Request__c poc = new Request__c( Opportunity__c = opp.Id, Status__c = 'Open');
        insert poc;
        Opportunity newOpp = [select Id,Has_Active_POCs__c from Opportunity where Id =: opp.Id];
        newOpp.Has_Active_POCs__c = false;
        update newOpp;
  		Account newAcct = [select Id, Has_Active_POCs__c from Account where Id =: acct.Id];
        newAcct.Has_Active_POCs__c = false;
        update newAcct;
        Test.startTest();
		OpportunityPocStatusBatchJob opsb = new OpportunityPocStatusBatchJob();
		Database.executeBatch(opsb);
        Test.stopTest();
        Opportunity newOpp1 = [select Id,Has_Active_POCs__c from Opportunity where Id =: opp.Id];
        Account newAcct1 = [select Id, Has_Active_POCs__c from Account where Id =: acct.Id];
		system.assertEquals(true, newOpp1.Has_Active_POCs__c);
		system.assertEquals(true, newAcct1.Has_Active_POCs__c);        
    }
}