objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Product_1__c</fullName>
        <label>Evaluation Product 1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10 on GX-V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Location_1__c</fullName>
        <label>Ship To - Location 1</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wan Emulator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address - Loc 1</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Email_Loc_2__c</fullName>
        <label>Contact Email - Loc 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Loc_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact - Loc 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA&apos;s (Contact - Loc 1)</relationshipLabel>
        <relationshipName>R00N500000021gyAEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t2CsEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product -Loc 1</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>RMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2CyEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NewRMAHelper.cls
/**
 *  Called by the Open RMA buttons.
 */

global class NewRMAHelper
{
    /**
     * A valid asset is status != 'Pending Return - xxx' and not in another RMA.
     */
    webService static String getValidAssetIds(String assetIdsStr)
    {
        String validAssetIds = '';
        Set<String> assetIds = splitAssetIds(assetIdsStr);
        assetIds = removeInvalidAssets(assetIds);
        if(!assetIds.isEmpty())
        {
            for(String assetId : assetIds)
            {
                validAssetIds += assetId;
                validAssetIds += ',';
            }
        }
        return validAssetIds;
    }
    
    webService static Boolean createRmaOnPOC(String assetIdsStr)
    {
        Set<String> assetIds = splitAssetIds(assetIdsStr);
        return createRmaWithAssetStatus(assetIds, null, 'Pending Return – Eval');
    }
    
    public static Boolean createRmaWithAssetStatus(Set<String> assetIds, String contactId, String assetStatus)
    {
        List<Asset> assets = [select Id, Product2Id, Contact.Email, POCRequest__r.Name, POCRequest__r.POC_Contact__c, POCRequest__r.Evaluation_Product_1__c, POCRequest__r.Ship_To_Location_1__c, AccountId from Asset where Id in :assetIds];
        if(!assets.isEmpty())
        {
            RMA__c rma = getNewRMA(assets[0], contactId);
            Savepoint sp = Database.setSavepoint();
            try
            {   
                upsert rma;
            }
            catch(Exception ex)
            {
                throw(ex);
            }
            
            List<RMA_Item__c> rmaItems = new List<RMA_Item__c>();
            Id rmaItemRecordTypeId = [select Id from RecordType where Name = 'Eval Return' and SobjectType = 'RMA_Item__c' limit 1].Id;
            for(Asset asset : assets)
            {
                RMA_Item__c rmaItem = getNewRMAItem(rma.Id, asset.Id, asset.Product2Id, rmaItemRecordTypeId);
                rmaItems.add(rmaItem);
                asset.Status = assetStatus;
                asset.Evaluation_End_Date__c = Date.today();
            }
            
            try
            {
                insert rmaItems;
                update assets;
                return true;
            }
            catch(Exception ex)
            {
                Database.rollback(sp); 
                throw(ex);
            }
        }
        return false;
    }
    
    public static Set<String> splitAssetIds(String assetIdsStr)
    {
        Set<String> assetIds = new Set<String>();
        if(assetIdsStr != null)
        {
            assetIds.addAll(assetIdsStr.replaceAll('\'', '').split(','));
        }
        return assetIds;
    }
    
    /**
     * Removes the selected assets that can't create RMA.
     */
    private static Set<String> removeInvalidAssets(Set<String> assetIds)
    {
        for(Asset asset : [select Id from Asset where Id in :assetIds and Status like '%Pending Return%'])
        {
            assetIds.remove(String.valueOf(asset.Id).substring(0,15));
        }
        for(RMA_Item__c rmaItem : [select Asset__c from RMA_Item__c where Asset__c in :assetIds and status__c <> 'Received'])
        {
            assetIds.remove(String.valueOf(rmaItem.Asset__c).substring(0,15));
        } 
        return assetIds;
    }
    
    private static RMA__c getNewRMA(Asset asset, String contactId)
    {
        RMA__c rma =  new RMA__c();
        Id rmaRecordTypeId = [select Id from RecordType where Name = 'Eval RMA' and SobjectType = 'RMA__c' limit 1].Id;
        rma.RecordTypeId = rmaRecordTypeId;
        rma.Type__c = 'Eval Return';
        rma.Status__c = 'Initiated';
        rma.Request__c = asset.POCRequest__r.Id;
        rma.Account__c = asset.AccountId;
        rma.Contact__c = contactId;
        rma.Contact_Email_Loc_2__c = asset.Contact.Email;
        rma.Contact_Loc_1__c = asset.POCRequest__r.POC_Contact__c;
        rma.Product__c = asset.POCRequest__r.Evaluation_Product_1__c; 
        rma.Address1__c = asset.POCRequest__r.Ship_To_Location_1__c;
        return rma;
    }
    
    private static RMA_Item__c getNewRMAItem(String rmaId, String assetId, String productId, String recordTypeId)
    {
        RMA_Item__c rmaItem = new RMA_Item__c();
        rmaItem.RMA__c = rmaId;
        rmaItem.Asset__c = assetId;
        rmaItem.Product2__c = productId;
        rmaItem.Type__c = 'Return - Refurbish and Stock';
        rmaItem.Status__c = 'Awaiting Return';
        rmaItem.RecordTypeId = recordTypeId;
        return rmaItem;
    }
    
    @isTest
    static void testGetValidAssetIds()
    {
        List<Asset> assets = createTestAssets();
        Asset asset1 = assets[0];
        Asset asset2 = assets[1];
        String assetIds = String.valueOf(asset1.Id).subString(0,15) + ',' + String.valueOf(asset2.Id).subString(0,15);
        
        //Success.
        System.assertNotEquals('', NewRMAHelper.getValidAssetIds(assetIds));
        
        //Tests when the status of asset is Pending Return.
        asset1.Status = 'Pending Return - Eval';
        update asset1;
        System.assertNotEquals('', NewRMAHelper.getValidAssetIds(assetIds));
        asset2.Status = 'Pending Return - CPO';
        update asset2;
        System.assertEquals('', NewRMAHelper.getValidAssetIds(assetIds));
        
        //Tests when asset is on an RMA.
        asset2.Status = 'Conditional PO';
        update asset2;
        Id rmaRecordTypeId = [select Id from RecordType where Name = 'Eval RMA' and SobjectType = 'RMA__c' limit 1].Id;
        RMA__c rma =  new RMA__c(Type__c = 'Eval Return', Status__c = 'Initiated', Account__c = asset1.AccountId, RecordTypeId = rmaRecordTypeId);
        insert rma;
        Id rmaItemRecordTypeId = [select Id from RecordType where Name = 'Eval Return' and SobjectType = 'RMA_Item__c' limit 1].Id;
        RMA_Item__c rmaItem = new RMA_Item__c(RMA__c = rma.Id, Asset__c = asset1.Id, Type__c = 'Return - Refurbish and Stock', Status__c = 'Not Dispatched', RecordTypeId = rmaItemRecordTypeId);
        insert rmaItem;
        System.assertNotEquals('', NewRMAHelper.getValidAssetIds(assetIds));
        rmaItem.Asset__c = asset2.Id;
        update rmaItem;
        System.assertEquals('', NewRMAHelper.getValidAssetIds(assetIds));
    }
    
    @isTest
    static void testCreateRMAOnPOC()
    {
        List<Asset> assets = createTestAssets();
        Asset asset1 = assets[0];
        Asset asset2 = assets[1];
        String assetIds = String.valueOf(asset1.Id).subString(0,15) + ',' + String.valueOf(asset2.Id).subString(0,15);
        
        system.assertEquals(true, NewRMAHelper.createRMAOnPOC(assetIds));
    }
    
    public static List<Asset> createTestAssets()
    {
        Account acc = new Account(Name = 'acme', Type = 'Eval');
        insert acc;
        Contact con = new Contact(LastName = 'acme', AccountId = acc.Id, Email = 'acme@acme.com');
        insert con;
        Product2 prd = new Product2(Name = 'acme');
        insert prd;
        List<Asset> assets = new List<Asset>();
        Asset asset1 = new Asset(Name = 'acme1', SerialNumber = 'acme1', Quantity = 1.00, Status = 'Conditional PO', Product2Id = prd.Id, AccountId = acc.Id, ContactId = con.Id);
        Asset asset2 = new Asset(Name = 'acme2', SerialNumber = 'acme2', Quantity = 1.00, Status = 'Conditional PO', Product2Id = prd.Id, AccountId = acc.Id, ContactId = con.Id);
        assets.add(asset1);
        assets.add(asset2);
        insert assets;
        return assets;
    }
}