objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>GMS_Needed__c</fullName>
        <label>GMS Ship To</label>
        <picklist>
            <picklistValues>
                <fullName>None Req&apos;d</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PhysicalProduct1__c</fullName>
        <label>Physical Product1</label>
        <picklist>
            <picklistValues>
                <fullName>NX700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 6700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 10700</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_1__c</fullName>
        <label>Quantity - Location 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment__c.object
<CustomObject>
    <description>Used to track shipments of assets outbound. Will update OR create assets and update the needed information for them when a shipment is made</description>
    <fields>
        <fullName>POC_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipment_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set all assets to this contact</inlineHelpText>
        <label>Shipment Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>set all shipment line assets to this contract</inlineHelpText>
        <label>Shipment Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Be_Swapped_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Be Swapped Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SHIP-{000}</displayFormat>
        <label>ShipmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShippingInputFormControllerTest.cls
@isTest
public class ShippingInputFormControllerTest
{
	  @isTest
    static void testShippingInputFormController()
    {
        Account account = new Account(Name = 'test shipment');
        insert account;
        Contact ct = new Contact(AccountId = account.Id, LastName = 'test ship');
        insert ct;
        Product2 prd = new Product2(Name='acme', Family='Product', IsActive=true, ProductCode='acme');
        insert prd;
        Asset asset = new Asset(Name = 'test', SerialNumber = '123456789012', AccountId = account.Id, ContactId = ct.Id, Product2Id=prd.Id);
        insert asset;
        Asset asset2 = new Asset(Name = 'test2', SerialNumber = '123456789013', AccountId = account.Id, ContactId = ct.Id, Product2Id=prd.Id);
        insert asset2;
        
        PageReference pageRef = new PageReference('/apex/ShippingInputForm?accountId=' + account.Id);
        Test.setCurrentPage(pageRef);
        
        ShippingInputFormController controller = new ShippingInputFormController();
        controller.SNSets = '123456789012, 1234567890ab';
        controller.Process();
        controller.Shipment.To_Be_Swapped_Asset__c = asset2.Id;
        controller.getProductList();
        controller.getPartNumberList();
        
        List<ShippingInputFormController.ShipLineInfo> lines = controller.ShippedLineList;
        System.assertEquals(2, lines.size());
        System.assertEquals(true, lines[0].AssetIsExisted);
        System.assertEquals(false, lines[1].AssetIsExisted);
        lines[1].SelectProductId = prd.Id;
        
        controller.Save();
        System.assertEquals(0, ApexPages.getMessages().size());
        List<Shipment__c> shipmentList = [select Shipment_Account__c, Shipment_Contact__c, Shipment_Contract__c from Shipment__c where Id = :controller.Shipment.Id limit 1];
        System.assertEquals(1, shipmentList.size());
        
        asset2 = [select Id, Status from Asset where Id=:asset2.Id limit 1];
        System.assertEquals('Pending Return – Support', asset2.Status);
    }
    
     @isTest
    static void testShippingInputFormControllerForPOC()
    {
       	
        Account account = new Account(Name = 'test shipment');
        insert account;
        Contact ct = new Contact(AccountId = account.Id, LastName = 'test ship',Email='abc@abc.com');
        insert ct;
        Product2 prd = new Product2(Name='EC-XS', Family='Product', IsActive=true, ProductCode='500210-001');
        insert prd;
        
        Id standardPricebookId = TestUtilities.getStandardPricebookId();
        Id opportunityId = TestUtilities.createTestOpportunity(account.Id, standardPricebookId);
        
        Request__c pocRequest = new Request__c();
        pocRequest.Opportunity__c = opportunityId;
        pocRequest.POC_Contact__c = ct.id;
        pocRequest.POC_Type__c='EdgeConnect';
        pocRequest.GMS_Needed__c = '';
        pocRequest.PhysicalProduct1__c = 'EC-XS';
        pocRequest.Quantity_Location_1__c = 1;
        insert pocRequest;
        //System.assert(pocRequest.id!=null);
        
        PageReference pageRef = new PageReference('/apex/ShippingInputForm?pocId=' + pocRequest.Id);
        Test.setCurrentPage(pageRef);
       	
        ShippingInputFormController controller = new ShippingInputFormController();
        controller.SNSets = '123456789012';
        controller.Process();
        controller.getProductList();
        controller.getPartNumberList();
        controller.Shipment.Ship_Date__c= Date.today();
        List<ShippingInputFormController.ShipLineInfo> lines = controller.ShippedLineList;
        //System.assert(controller.Shipment.POC_Request__c == pocRequest.Id);
        //System.assert(controller.ShippedLineList.size()==1);
        //System.assertEquals(false, lines[0].AssetIsExisted);
        controller.ShippedLineList[0].SelectProductId = prd.Id;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com');
    
        u.IsActive =true;
        System.runAs(u) {
            // The following code runs as user 'u' 
           controller.save();
            
        }
       	List<Shipment__c> shipmentList = [select Shipment_Account__c, Shipment_Contact__c, Shipment_Contract__c from Shipment__c where Id = :controller.Shipment.Id limit 1];
        System.assertEquals(1, shipmentList.size());
        
    }
    
    
    @isTest
    static void testGetAssetPartNumber()
    {
        
        Product2 p = new Product2(Name='acme', ProductCode='acme2');
        insert p;
        ReplaceablePartNumberMatrix__c entry = new ReplaceablePartNumberMatrix__c(Name='acme', Asset_PN__c='acme1', Product_PN__c='acme2');
        insert entry;
        System.assertEquals(1, ShippingInputFormController.getAssetPartNumber(p.Id).size());
    }
    
    @isTest
    static void testIsValidSerialNumber()
    {
        PageReference ref = new PageReference('/apex/ShippingInputFormInternal');
        Test.setCurrentPage(ref);
        ShippingInputFormController controller = new ShippingInputFormController();
        System.assert(controller.isValidSerialNumber('1234567890ab'));
        System.assert(!controller.isValidSerialNumber('1234567890ax'));
        System.assert(controller.isValidSerialNumber('12-34-56-78-90-ab'));
        System.assert(!controller.isValidSerialNumber('12-34-56-78-90-ab-'));
        System.assert(!controller.isValidSerialNumber('12-34-56-78-90ab'));
        System.assert(controller.isValidSerialNumber('1234.5678.90ab'));
        System.assert(!controller.isValidSerialNumber('1234.567890ab'));
        System.assert(!controller.isValidSerialNumber('1234.5678.90ab.'));
        System.assert(!controller.isValidSerialNumber('.1234.5678.90ab'));
    }
    
     
}