objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>GMS_Needed__c</fullName>
        <label>GMS Ship To</label>
        <picklist>
            <picklistValues>
                <fullName>None Req&apos;d</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_1__c</fullName>
        <label>Quantity - Location 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_2__c</fullName>
        <label>Quantity - Location 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VirtualProduct1__c</fullName>
        <label>Virtual Product1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unity Cloud Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VirtualProduct2__c</fullName>
        <label>Virtual Product2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSendWanOPPOCFulfillmentEmail.cls
@IsTest
public class TestSendWanOPPOCFulfillmentEmail {
    @isTest(SeeAllData=true)
    static void testVirtualPOCFulfillmentController_VX()
    {
        Account account = new Account(Name = 'acme');
        insert account;
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.FirstName = 'acme';
        contact.LastName = 'acme';
        contact.Email = 'abc@abc.com';
        insert contact;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = account.Id;
        //opportunity.Pricebook2Id = pricebookId;
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Product_Type__c='Both';
        opportunity.Solution_Type__c='Replication Acceleration';
        opportunity.Technical_Responsible__c=UserInfo.getUserId();
        insert opportunity;
        
        Request__c pocRequest = new Request__c();
        pocRequest.Opportunity__c = opportunity.Id;
        pocRequest.POC_Type__c = 'WAN Op';
        pocRequest.POC_Contact__c = contact.Id;
        pocRequest.GMS_Needed__c = 'Virtual';
        pocRequest.VirtualProduct1__c = 'VX-2000';
        //pocRequest.VirtualProduct2__c = 'VRX-2';
        pocRequest.Quantity_Location_1__c = 1;
        //pocRequest.Quantity_Location_2__c = 1;
        insert pocRequest;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(pocRequest);
        VirtualPOCFulfillmentController controller = new VirtualPOCFulfillmentController(sc);
        
        controller.addAsset();
        Integer maxIndex = controller.VirtualAssets.size() - 1;
        system.debug(controller.ProductOptions);
        for(Integer i = maxIndex; i >= 0; i--)
        {
            ApexPages.currentPage().getParameters().put('rmIndex', String.valueOf(i));
            controller.removeAsset();
        }
        controller.save();
        
        pocRequest.Send_Email__c=true;
        update pocRequest;
        Test.stopTest();
        //controller.saveAssets();
        //controller.setLicenseEncryption();
    }
    @isTest(SeeAllData=true)
    static void testVirtualPOCFulfillmentController_VRX()
    {
        Account account = new Account(Name = 'acme');
        insert account;
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.FirstName = 'acme';
        contact.LastName = 'acme';
        contact.Email = 'abc@abc.com';
        insert contact;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = account.Id;
        //opportunity.Pricebook2Id = pricebookId;
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Product_Type__c='Both';
        opportunity.Solution_Type__c='Replication Acceleration';
        opportunity.Technical_Responsible__c=UserInfo.getUserId();
        insert opportunity;
        
        Request__c pocRequest = new Request__c();
        pocRequest.Opportunity__c = opportunity.Id;
        pocRequest.POC_Type__c = 'WAN Op';
        pocRequest.POC_Contact__c = contact.Id;
        pocRequest.GMS_Needed__c = 'Virtual';
        //pocRequest.VirtualProduct1__c = 'VX-2000';
        pocRequest.VirtualProduct1__c ='VRX-2';
        pocRequest.Quantity_Location_1__c = 1;
        //pocRequest.Quantity_Location_2__c = 1;
        insert pocRequest;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(pocRequest);
        VirtualPOCFulfillmentController controller = new VirtualPOCFulfillmentController(sc);
        
        controller.addAsset();
        Integer maxIndex = controller.VirtualAssets.size() - 1;
        system.debug(controller.ProductOptions);
        for(Integer i = maxIndex; i >= 0; i--)
        {
            ApexPages.currentPage().getParameters().put('rmIndex', String.valueOf(i));
            controller.removeAsset();
        }
        controller.save();
        
        pocRequest.Send_Email__c=true;
        update pocRequest;
        Test.stopTest();
        //controller.saveAssets();
        //controller.setLicenseEncryption();
    }
}