objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Product_1__c</fullName>
        <label>Evaluation Product 1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10 on GX-V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsAllVirtual__c</fullName>
        <formula>IF( 

OR( 
LEFT(TEXT( Evaluation_Product_1__c ) ,1) = &apos;N&apos;,
LEFT(TEXT( Evaluation_Product_2__c ) ,1) = &apos;N&apos;, 
CONTAINS(TEXT( Evaluation_Product_1__c ) ,&apos;GX-1000&apos;), 
CONTAINS(TEXT( Evaluation_Product_2__c ) ,&apos;GX-1000&apos;),
NOT(ISBLANK(TEXT( PhysicalProduct1__c )))

), 0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsAllVirtual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Location_1__c</fullName>
        <label>Ship To - Location 1</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <inlineHelpText>This is the date the POC request is approved to run to</inlineHelpText>
        <label>Target End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wan Emulator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address - Loc 1</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Loc_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact - Loc 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA&apos;s (Contact - Loc 1)</relationshipLabel>
        <relationshipName>R00N500000021gyAEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product -Loc 1</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>RMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2CyEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PocRequestAutomationHelper.cls
/*
* Includes some method for POC Request Automation
*/
public class PocRequestAutomationHelper
{
    public static final String EvalRmaRecordTypeId = '012500000005H0o';
    public static final String EvalRMAItemRecordTypeId = '012500000005H0y';
    
    public static void removePocLinkOnAsset(Set<Id> pocIds)
    {
        List<Request__c> requests = [select Id, Status__c, (select POCRequest__c from Assets__r) from Request__c where Id in :pocIds];
        List<Asset> assets = new List<Asset>();
        for(Request__c request : requests)
        {
            for(Asset asset : request.Assets__r)
            {
                asset.POCRequest__c = null;
                assets.add(asset);
            }
        }
        try
        {
            Database.update(assets, false);
        }
        catch(DmlException ex)
        {
            throw new PocRequestAutomationException(ex.getMessage());
        }
    }
    
    public static void removePocLinkOnAssetAndSetStatus(Set<Id> assetIds)
    {
        List<Asset> assets = new List<Asset>();
        for(Id assetId : assetIds)
        {
            assets.add(new Asset(Id=assetId, POCRequest__c=null, Status='Silver Peak Inventory'));
        }
        try
        {
            Database.update(assets, false);
        }
        catch(DmlException ex)
        {
            throw new PocRequestAutomationException(ex.getMessage());
        }
    }
    
    public static void CreateEvalRMA(Set<Id> pocIds)
    {
        List<RMA__c> rmas = new List<RMA__c>();
        List<Asset> assets = new List<Asset>();
        List<Asset> partVirtualAssets = new List<Asset>();
        List<Asset> changeAssets = new List<Asset>();
        List<Asset> trashyAssets = new List<Asset>();
        Set<Id> AssetIds = new Set<Id>();
        List<Opportunity> opportunities = new List<Opportunity>();
        Set<Id> opportunityIds = new Set<Id>();
        
        Map<Id, List<RMA_Item__c>> rmaItemMap = new Map<Id, List<RMA_Item__c>>(); //key: poc id, value: rma line items
        List<Request__c> requests = [select Id, Name, Status__c, IsAllVirtual__c, POC_Contact__c, Evaluation_Product_1__c, Ship_To_Location_1__c, Opportunity__r.AccountId, Opportunity__r.Type, Opportunity__r.StageName, Opportunity__r.Amount, (select Id, Product2Id, Product2.Product_Family_Clean__c, Hosted_GMS__c, Account.Name from Assets__r), (select Id from RMAs__r where RecordTypeId=:EvalRmaRecordTypeId) from Request__c where Id in :pocIds];
        
        Id accountId;
        List<Account> accounts = [select Id, Name from Account where Name = 'EMAIL SUPPORT CONTACTS'];
        if(accounts != null && accounts.size() > 0)
        {
            accountId = accounts[0].Id;
        }
        else
        {
            throw new PocRequestAutomationException('Email support contacts not found.');
        }
        
        for(Request__c request : requests)
        {
            if(request.RMAs__r.size() == 0)
            {
                RMA__c rma = new RMA__c(Account__c=request.Opportunity__r.AccountId, RecordTypeId=EvalRmaRecordTypeId, Request__c=request.Id, Status__c='Initiated', Type__c='Eval Return', Contact_Loc_1__c=request.POC_Contact__c, Product__c=request.Evaluation_Product_1__c, Address1__c=request.Ship_To_Location_1__c);
                List<RMA_Item__c> items = new List<RMA_Item__c>();
                for(Asset asset : request.Assets__r)
                {
                    if(asset.Product2.Product_Family_Clean__c == 'Virtual')
                    { 
                        if(asset.Hosted_GMS__c)
                        {
                            asset.AccountId = accountId;
                            changeAssets.add(asset);
                        }
                        else
                        {
                            partVirtualAssets.add(asset);
                        }
                    }
                    else
                    {
                        items.add(new RMA_Item__c(Asset__c=asset.Id, Product2__c=asset.Product2Id, RecordTypeId=EvalRMAItemRecordTypeId, Type__c='Return - Refurbish and Stock', Status__c='Not Dispatched'));
                        assets.add(asset);
                    }
                }
                trashyAssets.addAll(partVirtualAssets);
                partVirtualAssets.clear();
                if(items.size() > 0)
                {
                    rmas.add(rma);
                }
                rmaItemMap.put(request.Id, items);
            }
            if(request.Opportunity__r.Type == 'Marketplace' && request.Opportunity__r.Amount == 0)
            {
                //request.Opportunity__r.StageName = 'Closed Dead';
                opportunityIds.add(request.Opportunity__c);
            }    
        }
        SavePoint sp = Database.setSavePoint();
        opportunities = [select Id, StageName from Opportunity where Id in :opportunityIds];
        for(Opportunity opportunity : opportunities)
        {
            opportunity.StageName = 'Closed Dead';
            opportunity.Bypassing_Validation__c = true;
        }
        try
        {
            update opportunities;
            upsert rmas;
            for(Asset asset : trashyAssets)
            {
                AssetIds.add(asset.Id);
            }
            deleteAssets(AssetIds);
            update changeAssets;
        }
        catch(DmlException ex)
        {
            Database.rollback(sp);
            throw new PocRequestAutomationException(ex.getMessage());
        }
        List<RMA_Item__c> rmaItems = new List<RMA_Item__c>();
        for(RMA__c rma : rmas)
        {
            List<RMA_Item__c> items = rmaItemMap.get(rma.Request__c);
            if(items != null)
            {
                for(RMA_Item__c item : items)
                {
                    item.RMA__c = rma.Id;
                    rmaItems.add(item);
                }
            }
        }
        try
        {
            upsert rmaItems;
        }
        catch(DmlException ex)
        {
            Database.rollback(sp);
            throw new PocRequestAutomationException(ex.getMessage());
        }
        for(Asset asset : assets)
        {
            asset.Status = 'Pending Return – Eval';
            asset.Evaluation_End_Date__c = Date.today();
        }
        try
        {
            update assets;
        }
        catch(DmlException ex)
        {
            Database.rollback(sp);
            throw new PocRequestAutomationException(ex.getMessage());
        }
    }
    
    @Future
    public static void deleteAssets(Set<Id> assetsId)
    {
        Database.delete([select Id from asset where Id in: assetsId], false);
    }
    
    public static void closeRMAs(Set<Id> pocIds)
    {
        List<RMA__c> rmas = new List<RMA__c>();
        List<Request__c> requests = [select Id, (select Id from RMAs__r) from Request__c where Id in :pocIds];
        System.debug(requests);
        for(Request__c request : requests)
        {
            for(RMA__c rma : request.RMAs__r)
            {
                rma.Status__c = 'Closed';
                rmas.add(rma);
            }
        }
        try
        {
            update rmas;
        }
        catch(DmlException ex)
        {
            throw new PocRequestAutomationException(ex.getMessage());
        }
    }
    
    public static void updateAssetDate(Set<Id> pocIds)
    {
        List<Request__c> requests = [select Id, Target_End_Date__c, (select POCRequest__c from Assets__r) from Request__c where Id in :pocIds];
        List<Asset> assets = new List<Asset>();
        for(Request__c request : requests)
        {
            for(Asset asset : request.Assets__r)
            {
                asset.Evaluation_End_Date__c = request.Target_End_Date__c;
                assets.add(asset);
            }
        }
        try
        {
            update assets;
        }
        catch(DmlException ex)
        {
            throw new PocRequestAutomationException(ex.getMessage());
        }
    }
    
    public class PocRequestAutomationException extends Exception
    {
    }
    
    // Test the class when poc is not all virtual.
    @IsTest
    static void testPocRequestAutomationHelper()
    {
        
        Account silverPeakAccount = new Account(Name='Silver Peak Systems',EC_Customer_Date__c=Date.today());
        insert silverPeakAccount;
        Account supportAccount = new Account(Name='EMAIL SUPPORT CONTACTS',EC_Customer_Date__c=Date.today());
        insert supportAccount;
        Account account = new Account(Name='acme',EC_Customer_Date__c=Date.today());
        insert account;
        AccountTeamMember teamMember=new AccountTeamMember(AccountId=account.Id,UserId=UserInfo.getUserId(),TeamMemberRole='Account Manager');
        insert teamMember;
        
        User u = [select Id from User where Id != :UserInfo.getUserId() and IsActive = true limit 1];
        Opportunity opp = new Opportunity(AccountId=account.Id, Name='test', StageName='Open', CloseDate=Date.today(), ForecastCategoryName='Pipeline', OwnerId=u.Id);
        opp.Product_Type__c='Both';
        insert opp;
                Test.startTest();

        Request__c request = new Request__c(Opportunity__c=opp.Id, Evaluation_Product_1__c='NX 1700');
        insert request;
        
        Product2 product = new Product2(Name = 'test', IsActive = true, Family = 'Virtual Image');
        insert product;
        Asset asset = new Asset(Name='test', AccountId=account.Id, PocRequest__c=request.Id,Silver_Peak_Account__c=account.id);
        insert asset;
        Asset asset2 = new Asset(Name='test', AccountId=account.Id, PocRequest__c=request.Id,Silver_Peak_Account__c=account.id);
        insert asset2;
        
        
        Asset asset3 = new Asset(Name='test', AccountId=account.Id, PocRequest__c=request.Id, Product2Id = product.Id,Silver_Peak_Account__c=account.id);
        insert asset3;
                Test.stopTest();

        /*
        request.Status__c = 'Pending Return';
        update request;
        
request = [select Id, IsAllVirtual__c, (select Id, Status__c from RMAs__r) from Request__c where Id=:request.Id limit 1];
System.assertEquals(1, request.RMAs__r.size());



List<RMA_Item__c> items = [select Id, Status__c, Asset__c from RMA_Item__c where RMA__r.Request__c=:request.Id];
System.assertEquals(2, items.size());

items[0].Status__c = 'Received';
update items[0];

asset = [select Id, Status, PocRequest__c from Asset where Id=:items[0].Asset__c limit 1];
System.assertEquals('Silver Peak Inventory', asset.Status);
System.assertEquals(null, asset.PocRequest__c);

request.Status__c = 'Closed - Returned';
update request;


request = [select Id, (select Id, Status__c from RMAs__r) from Request__c where Id=:request.Id limit 1];
System.assertEquals('Closed', request.RMAs__r[0].Status__c);

request.Target_End_Date__c = Date.today().addDays(1);
update request;
*/
        
    } 
}