objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>ActiveForNotices__c</fullName>
        <formula>If(
OR(
 ISPICKVAL( Status__c ,&apos;Shipped&apos; ),
 ISPICKVAL( Status__c ,&apos;Shipped - Extended&apos; )
),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActiveForNotices</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sending_Reminder_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sending Reminder Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <inlineHelpText>This is the date the POC request is approved to run to</inlineHelpText>
        <label>Target End Date</label>
        <type>Date</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PocRequestNotification.cls
/*
 * Updates the SendingReminderEmail field to true when TargetEndDate on Requests is 10 days after today, or just today.
 * An email will be sent out with a workflow.
 */
global class PocRequestNotification implements Schedulable
{
    global void execute(SchedulableContext sc)
    {
        System.debug('POC Request Notiifcation started '+ Datetime.now());
        List<Request__c> requests = [select Id, Opportunity__c, Opportunity__r.Account.OwnerId from Request__c where ActiveForNotices__c = 1 and Target_End_Date__c=:Date.today().addDays(5)];
        if(requests!=null)
        {
            System.debug('POC Request Pending Expiring count '+ requests.size());
        }
        for(Request__c request : requests)
        {
            request.Sending_Reminder_Email__c = true;
        }
        Database.SaveResult[] results = Database.update(requests, false);
        SilverPeakUtils.logDatabaseError(requests, results);
        
        List<Request__c> requests2 = [select Id, Opportunity__c, Opportunity__r.Account.OwnerId from Request__c where ActiveForNotices__c = 1 and Target_End_Date__c=:Date.today()];
        if(requests2!=null)
        {
            System.debug('POC Request Expired count '+ requests2.size());
        }
        for(Request__c request : requests2)
        {
            request.Sending_Reminder_Email__c = true;
            request.Status__c = 'Pending Return';
        }
        Database.SaveResult[] results2 = Database.update(requests2, false);
        SilverPeakUtils.logDatabaseError(requests2, results2);
		System.debug('POC Request Notiifcation ended '+ Datetime.now());
        /*requests = [select Id, Opportunity__c, Opportunity__r.Account.OwnerId from Request__c where ActiveForNotices__c = 1 and Target_End_Date__c=:Date.today().addDays(1)];
        for(Request__c request : requests)
        {
            request.Sending_Reminder_Invitation__c = true;
        }
        try
        {
            update requests;
        }
        catch(Exception ex)
        {
            SilverPeakUtils.logException(ex);
        }*/
    }
    
    @isTest
    static void testPocRequestNotification()
    {
        Account supportAccount = new Account(Name='EMAIL SUPPORT CONTACTS');
        insert supportAccount;
        Account account = new Account(Name='acme');
        insert account;
        Opportunity opp = new Opportunity(AccountId=account.Id, Name='test', StageName='Open', CloseDate=Date.today(), ForecastCategoryName='Pipeline');
        opp.Product_Type__c='Both';
        insert opp;
        Request__c request = new Request__c(Opportunity__c=opp.Id, Status__c='Shipped', Target_End_Date__c=Date.today());
        insert request;
        
        PocRequestNotification notify = new PocRequestNotification();
        notify.execute(null);
    }
}