objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Product_1__c</fullName>
        <label>Evaluation Product 1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10 on GX-V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Evaluation_Product_2__c</fullName>
        <label>Evaluation Product 2</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10 on GX-V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_1__c</fullName>
        <label>Quantity - Location 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_2__c</fullName>
        <label>Quantity - Location 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>RMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestDeleteRMAForApprovedPendRet.cls
@IsTest	
public class TestDeleteRMAForApprovedPendRet {
    @IsTest	
    public static void deleteRMA()
    {
        Account acc = new Account(Name='testECPOC');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Discovery';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Product_Type__c='Both';
        opportunity.Technical_Responsible__c=UserInfo.getUserId();
        insert opportunity;
        
        Request__c request = new Request__c(POC_Contact__c = contact.Id);
        request.POC_Type__c='EdgeConnect';
        request.Opportunity__c= opportunity.id;
        request.Evaluation_Product_1__c='EC-XS';
        request.Evaluation_Product_2__c='EC-XS';
        request.Quantity_Location_1__c=1;
        request.Quantity_Location_2__c=1;
        request.Status__c='Pending Return';
        insert request;
        Product2 product = new Product2();
        product.Name = 'EC-XS';
        product.ProductCode = 'EC-XS';
        product.Model__c = 'EC-XS';
        product.Family='Product';
        insert product;
        
        Asset asset= new Asset();
        asset.Name = '001BBC039649_t';
        asset.SerialNumber = '001BBC039649_t';
        asset.AccountId = acc.Id;
        asset.Product2Id = product.Id;
        asset.Status = 'Customer Owned';
        asset.Quantity = 1;
        asset.POCRequest__c=request.Id;
        insert asset;
        Test.startTest();
        NewRMAHelper.createRmaOnPOC(string.valueOf(asset.Id));
        
        
        List<RMA__c> rmaItem=[Select Id from RMA__C where Request__c=:request.Id];
        System.assert(rmaItem!=null && rmaItem.size()>0);
        Profile prof = [SELECT Id FROM Profile WHERE Name='9-Operations Manager']; 
        User usr = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = prof.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com');
        
        usr.IsActive =true;
        insert usr;
        System.runAs(usr){
            
            request.Status__c='Shipped - Extended';
            update request;
            
        }
        rmaItem=null;
    	rmaItem=[Select Id from RMA__c where Request__c=:request.Id];
        System.assert(rmaItem.size()==0);
        Test.stopTest();
    }
}