objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Extension_Justification__c</fullName>
        <inlineHelpText>Input your justification and resubmit for approval</inlineHelpText>
        <label>Extension Justification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_End_Date__c</fullName>
        <label>Requested End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <inlineHelpText>This is the date the POC request is approved to run to</inlineHelpText>
        <label>Target End Date</label>
        <type>Date</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/POCExtensionController.cls
public class POCExtensionController {
    
    public Request__c POCRequest{get;set;}
    
    public POCExtensionController(ApexPages.StandardController controller)
    {
        Id pocId=controller.getId();
        POCRequest= new Request__c();
        POCRequest=[Select Id,Status__c, Target_End_Date__c, POC_Type__c,Requested_End_Date__c,Extension_Justification__c from Request__c where Id=:pocId];
        System.debug(pocId);
        
        if(POCRequest.Status__c=='Pending Return')
        {
            POCRequest.Requested_End_Date__c=Date.today().addDays(10);
        }
        else
        {
            if(POCRequest.Target_End_Date__c!=null)
            {
                POCRequest.Requested_End_Date__c=POCRequest.Target_End_Date__c.addDays(10);
            }
            
        }
        
    }
    public PageReference SaveExtension()
    {
        boolean isValid=true;
        // Validate the extension request 
        
        if(POCRequest.Requested_End_Date__c==null )
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter Extend To Date.'));
            isValid=false;
        }
        if(String.isblank(POCRequest.Extension_Justification__c) )
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter the reason for POC Extension.'));
            isValid=false;
        }
        if(!isValid)
        {
            return null;
        }
        try
        {
            update pocRequest;
            // Call the approval process
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Extension request for approval.');
            req1.setObjectId(pocRequest.id);
            // Submit the approval request for the account
            Approval.ProcessResult result = Approval.process(req1);
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
            return null;
        }
        // save the extension request 
        
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Succeeded.<script type="text/javascript">opener.location="/'+pocRequest.Id+'";setTimeout("window.close()", 3000)</script>'));
        return null;
    }
}