objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CmaConvertComponentController.cls
/*
* Controller for CmaConvertComponent
*/
public class CmaConvertComponentController
{
    public List<CmaInfo> Cmas
    {
        get
        {
            Cmas = new List<CmaInfo>();
            if(CmaRecordId != null)
            {
                CmaInfo info = new CmaInfo();
                List<RMA_Item__c> rmaItems = [select Id, Asset__c, Asset__r.Model__c, Asset__r.SerialNumber, Asset__r.Contract_Type__c,
                                                Asset__r.Contract_End__c from RMA_Item__c where RMA__c = :CmaRecordId order by Asset__r.Model__c];
                for(RMA_Item__c item : rmaItems)
                {
                    String model = item.Asset__r.Model__c;
                    model = (model == null) ? '' : model;
                    if(model.contains('NX')) //no contract on NX
                    {
                        info.NxModel = item.Asset__r.Model__c;
                        info.NxSerialNumber = item.Asset__r.SerialNumber;
                    }
                    if(model.contains('VX'))
                    {
                        info.VxModel = item.Asset__r.Model__c;
                        info.VxSerialNumber = item.Asset__r.SerialNumber;
                        info.ContractType = item.Asset__r.Contract_Type__c;
                        info.ContractEndDate = item.Asset__r.Contract_End__c;
                    }
                }
                Cmas.add(info);
            }
            return Cmas;
        }
        set;
    }
    public String CmaRecordId { get; set; }

    public class CmaInfo
    {
        public String NxModel { get; set; }
        public String VxModel { get; set; }
        public String NxSerialNumber { get; set; }
        public String VxSerialNumber { get; set; }
        public String ContractType { get; set; }
        public Date ContractEndDate { get; set; }
    }
}