objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShipToAddressAdditional__c</fullName>
        <label>Ship To Street Additional</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToAddress__c</fullName>
        <inlineHelpText>The maximum amount of characters allowed is 60.  Please use Ship to Street Additional field to enter additional characters.</inlineHelpText>
        <label>Ship To Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToCity__c</fullName>
        <label>Ship To City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToCountry__c</fullName>
        <label>Ship To Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Saint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ShipToPostalCode__c</fullName>
        <label>Ship To Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToStateOrProvince__c</fullName>
        <label>Ship To State/Province</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N500000021gyXEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_address__c</fullName>
        <label>Ship-To Address</label>
        <type>TextArea</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EditRMALineAddressController.cls
/*
 * Controller of page EditRMALineAddress
 */
global with sharing class EditRMALineAddressController 
{
    private RMA_Item__c item;
    
    public EditRMALineAddressController(ApexPages.StandardController controller) 
    {
        item = (RMA_Item__c)controller.getRecord();
    }
    
    @RemoteAction
    global static List<CountryStateTable__c> getStateList(String country)
    {
        return [select StateCode__c, StateName__c from CountryStateTable__c where Country__c=:country order by StateName__c];
    }
    
    public PageReference save()
    {
        if(!isValidState())
        {
            return null;
        }
        
        try
        {
            item.Ship_to_address__c = NewRMAController.concateAddress(item.ShipToAddress__c, item.ShipToAddressAdditional__c, item.ShipToCity__c, item.ShipToStateOrProvince__c, item.ShipToPostalCode__c, item.ShipToCountry__c, item.Ship_To_Contact__r.FirstName, item.Ship_To_Contact__r.LastName, item.Contact_Phone__c);
            upsert item;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Updated successfully<script>top.opener.location="/'+item.Id+'";top.close();</script>'));
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
        }
        return null;
    }
    
    private Boolean isValidState()
    {
        List<CountryStateTable__c> states = getStateList(item.ShipToCountry__c);
        if(states.size() > 0)
        {
            Boolean foundState = false;
            for(CountryStateTable__c state : states)
            {
                if(state.StateCode__c == item.ShipToStateOrProvince__c)
                {
                    foundState = true;
                    break;
                }
            }
            if(!foundState)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'You must choose a Ship to State/Province.'));
                return false;
            }
        }
        return true;
    }
    
    @isTest
    static void testEditRMALineAddressController()
    {
        CountryStateTable__c state = new CountryStateTable__c(Name='acme', Country__c='United States', StateCode__c='CA', StateName__c='California');
        insert state;
        
        RMA_Item__c item = new RMA_Item__c(ShipToCountry__c='United States', ShipToStateOrProvince__c='CA');
        ApexPages.StandardController ctrl = new ApexPages.StandardController(item);
        EditRMALineAddressController controller = new EditRMALineAddressController(ctrl);
        
        List<CountryStateTable__c> states = getStateList('United States');
        controller.save();
    }
}