objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email -Loc 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone -Loc 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Delivery_Class__c</fullName>
        <label>Delivery Class</label>
        <picklist>
            <picklistValues>
                <fullName>Next Business Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShipToAddressAdditional__c</fullName>
        <label>Ship To Street Additional</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToAddress__c</fullName>
        <inlineHelpText>The maximum amount of characters allowed is 60.  Please use Ship to Street Additional field to enter additional characters.</inlineHelpText>
        <label>Ship To Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToCity__c</fullName>
        <label>Ship To City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToCountry__c</fullName>
        <label>Ship To Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Saint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ShipToPostalCode__c</fullName>
        <label>Ship To Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToStateOrProvince__c</fullName>
        <label>Ship To State/Province</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NoDispatchForECOneYearProductTest.cls
@IsTest
public class NoDispatchForECOneYearProductTest {
    
    /*
 	 @IsTest 
    public static void NoDispatchForECOneYearProduct_OperationsProfile()
    {
        Account acc = new Account(Name='acme', Type='Eval');
        insert acc;
        Contact con = new Contact(LastName='acme', AccountId=acc.Id);
        con.MailingStreet='address1 \r\n address2';
        insert con;
        List<Product2> pros = new List<Product2> { 
            new Product2(Name='EC-M',Family='Product', ProductCode='EC-M') };
                insert pros;
        Product2 pro = new Product2(Name='EC-M', Family='Product', ProductCode='acme', Model__c='acme', RMA_Primary_Replacement__c=pros[0].Id);
        insert pro;
        Asset asset = new Asset(Name='acme', SerialNumber='acme', Quantity=1.00,Status='Customer Owned', Product2Id=pro.Id, AccountId=acc.Id, ContactId=con.Id);
        insert asset;
        NewRMAController controller = new NewRMAController();
        Case caseInfo = new Case(Subject='acme', Status='On Hold', Origin='Email', AssetId=asset.Id, AccountId=acc.Id, ContactId=con.Id);
        caseInfo.Type = controller.getRecordTypeId('System Change Request', 'Case');
        insert caseInfo;
        
        PageReference page = new PageReference('/newrma?id=' + caseInfo.Id);
        Test.setCurrentPageReference(page);
        controller = new NewRMAController();
        controller.getRMA().Type__c = 'Return for Repair'; 
        controller.getRMAItem().Delivery_Class__c = 'Next Business Day';
        List<NewRMAController.ProductInfo> proInfos = new List<NewRMAController.ProductInfo> {
            new NewRMAController.ProductInfo('System'),
                new NewRMAController.ProductInfo('HDD'),
                new NewRMAController.ProductInfo('SSD'),
                new NewRMAController.ProductInfo('Power Supply') };
                    proInfos[0].Selected = true;
        proInfos[1].Selected = false;
        proInfos[2].Selected = false;
        proInfos[3].Selected = false;
        
        controller.Products = proInfos;
        controller.getContact().LastName = 'acme';
        controller.getRMAItem().Contact_Email__c = 'test@test.com';
        controller.getRMAItem().Contact_Phone__c = '123456789';
        controller.getRMAItem().ShipToCountry__c = 'USA';
        controller.getRMAItem().ShipToAddress__c = 'acme';
        controller.getRMAItem().ShipToAddressAdditional__c = 'acme';
        controller.getRMAItem().ShipToCity__c = 'acme';
        controller.getRMAItem().ShipToStateOrProvince__c = 'acme';
        controller.getRMAItem().ShipToPostalCode__c = '100000';
        controller.isEntitledForRMA(asset.Id);
        controller.getDeliveryClasses();
        controller.previous();
        controller.next();
        controller.getRMATypes();
        controller.save();
        controller.cancel();
        controller.createCase();
        NewRMAController.loadContactFromCase(null);
        
        con.Email = 'test@test.com';
        update con;
        PageReference page2 = new PageReference('/newrma?id=' + acc.Id);
        Test.setCurrentPageReference(page2);
        controller.getRMA().Type__c  = 'Advance Replace';
        controller.saveAndNew();
        RMA__c rma = new RMA__c();
        RMA_Item__c rmaItem = new RMA_Item__c();
        controller.setRMA(rma);
        controller.setRMAItem(rmaItem);
        controller.setContact(con);
        NewRMAController.parseAssetAddress('acme');
        controller.save();
       
        
        Profile p = [SELECT Id FROM Profile WHERE Name='9-Operations Manager']; 
        User u = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com');
    
        u.IsActive =true;
        System.runAs(u) {
            // The following code runs as user 'u' 
           
            RMA__c updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
            updatedRMA.Status__c ='Dispatched';
            update updatedRMA;
           
            
        }
        
        
        
    }
    
     @IsTest 
    public static void NoDispatchForECOneYearProduct_NonOperationsProfile()
    {
        Account acc = new Account(Name='acme', Type='Eval');
        insert acc;
        Contact con = new Contact(LastName='acme', AccountId=acc.Id);
        con.MailingStreet='address1 \r\n address2';
        insert con;
        List<Product2> pros = new List<Product2> { 
            new Product2(Name='EC-M', Family='Product',ProductCode='EC-M') };
                insert pros;
        Product2 pro = new Product2(Name='EC-M', Family='Product', ProductCode='EC-M', Model__c='EC-M', RMA_Primary_Replacement__c=pros[0].Id);
        insert pro;
        Asset asset = new Asset(Name='acme', SerialNumber='acme', Quantity=1.00,Status='Customer Owned', Product2Id=pro.Id, AccountId=acc.Id, ContactId=con.Id);
        insert asset;
        NewRMAController controller = new NewRMAController();
        Case caseInfo = new Case(Subject='acme', Status='On Hold', Origin='Email', AssetId=asset.Id, AccountId=acc.Id, ContactId=con.Id);
        caseInfo.Type = controller.getRecordTypeId('System Change Request', 'Case');
        insert caseInfo;
        
        PageReference page = new PageReference('/newrma?id=' + caseInfo.Id);
        Test.setCurrentPageReference(page);
        controller = new NewRMAController();
        controller.getRMA().Type__c = 'Return for Repair'; 
        controller.getRMAItem().Delivery_Class__c = 'Next Business Day';
        List<NewRMAController.ProductInfo> proInfos = new List<NewRMAController.ProductInfo> {
            new NewRMAController.ProductInfo('System'),
                new NewRMAController.ProductInfo('HDD'),
                new NewRMAController.ProductInfo('SSD'),
                new NewRMAController.ProductInfo('Power Supply') };
                    proInfos[0].Selected = true;
        proInfos[1].Selected = false;
        proInfos[2].Selected = false;
        proInfos[3].Selected = false;
        
        controller.Products = proInfos;
        controller.getContact().LastName = 'acme';
        controller.getRMAItem().Contact_Email__c = 'test@test.com';
        controller.getRMAItem().Contact_Phone__c = '123456789';
        controller.getRMAItem().ShipToCountry__c = 'USA';
        controller.getRMAItem().ShipToAddress__c = 'acme';
        controller.getRMAItem().ShipToAddressAdditional__c = 'acme';
        controller.getRMAItem().ShipToCity__c = 'acme';
        controller.getRMAItem().ShipToStateOrProvince__c = 'acme';
        controller.getRMAItem().ShipToPostalCode__c = '100000';
        controller.isEntitledForRMA(asset.Id);
        controller.getDeliveryClasses();
        controller.previous();
        controller.next();
        controller.getRMATypes();
        controller.save();
        controller.cancel();
        controller.createCase();
        NewRMAController.loadContactFromCase(null);
        
        con.Email = 'test@test.com';
        update con;
        PageReference page2 = new PageReference('/newrma?id=' + acc.Id);
        Test.setCurrentPageReference(page2);
        controller.getRMA().Type__c  = 'Advance Replace';
        controller.saveAndNew();
        RMA__c rma = new RMA__c();
        RMA_Item__c rmaItem = new RMA_Item__c();
        controller.setRMA(rma);
        controller.setRMAItem(rmaItem);
        controller.setContact(con);
        NewRMAController.parseAssetAddress('acme');
        controller.save();
       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='testUserSA@uniquetest.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testUserSA@uniquetest.com');
        	u.IsActive =true;
        	
        	System.runAs(u) {

            RMA__c updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
        	
            updatedRMA.Status__c ='Dispatched';
            update updatedRMA;
            updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
            System.assertEquals('Initated', updatedRMA.Status__c);
        }
    }
    
     @IsTest 
    public static void DispatchForECOneYearProductEvalStatus_NonOperationsProfile()
    {
        Account acc = new Account(Name='acme', Type='Eval');
        insert acc;
        Contact con = new Contact(LastName='acme', AccountId=acc.Id);
        con.MailingStreet='address1 \r\n address2';
        insert con;
        List<Product2> pros = new List<Product2> { 
            new Product2(Name='EC-M', Family='Product',ProductCode='EC-M') };
                insert pros;
        Product2 pro = new Product2(Name='EC-M', Family='Product', ProductCode='EC-M', Model__c='EC-M', RMA_Primary_Replacement__c=pros[0].Id);
        insert pro;
        Asset asset = new Asset(Name='acme', SerialNumber='acme', Quantity=1.00,Status='Customer Evaluation', Product2Id=pro.Id, AccountId=acc.Id, ContactId=con.Id);
        insert asset;
        NewRMAController controller = new NewRMAController();
        Case caseInfo = new Case(Subject='acme', Status='On Hold', Origin='Email', AssetId=asset.Id, AccountId=acc.Id, ContactId=con.Id);
        caseInfo.Type = controller.getRecordTypeId('System Change Request', 'Case');
        insert caseInfo;
        
        PageReference page = new PageReference('/newrma?id=' + caseInfo.Id);
        Test.setCurrentPageReference(page);
        controller = new NewRMAController();
        controller.getRMA().Type__c = 'Return for Repair'; 
        controller.getRMAItem().Delivery_Class__c = 'Next Business Day';
        List<NewRMAController.ProductInfo> proInfos = new List<NewRMAController.ProductInfo> {
            new NewRMAController.ProductInfo('System'),
                new NewRMAController.ProductInfo('HDD'),
                new NewRMAController.ProductInfo('SSD'),
                new NewRMAController.ProductInfo('Power Supply') };
                    proInfos[0].Selected = true;
        proInfos[1].Selected = false;
        proInfos[2].Selected = false;
        proInfos[3].Selected = false;
        
        controller.Products = proInfos;
        controller.getContact().LastName = 'acme';
        controller.getRMAItem().Contact_Email__c = 'test@test.com';
        controller.getRMAItem().Contact_Phone__c = '123456789';
        controller.getRMAItem().ShipToCountry__c = 'USA';
        controller.getRMAItem().ShipToAddress__c = 'acme';
        controller.getRMAItem().ShipToAddressAdditional__c = 'acme';
        controller.getRMAItem().ShipToCity__c = 'acme';
        controller.getRMAItem().ShipToStateOrProvince__c = 'acme';
        controller.getRMAItem().ShipToPostalCode__c = '100000';
        controller.isEntitledForRMA(asset.Id);
        controller.getDeliveryClasses();
        controller.previous();
        controller.next();
        controller.getRMATypes();
        controller.save();
        controller.cancel();
        controller.createCase();
        NewRMAController.loadContactFromCase(null);
        
        con.Email = 'test@test.com';
        update con;
        PageReference page2 = new PageReference('/newrma?id=' + acc.Id);
        Test.setCurrentPageReference(page2);
        controller.getRMA().Type__c  = 'Advance Replace';
        controller.saveAndNew();
        RMA__c rma = new RMA__c();
        RMA_Item__c rmaItem = new RMA_Item__c();
        controller.setRMA(rma);
        controller.setRMAItem(rmaItem);
        controller.setContact(con);
        NewRMAController.parseAssetAddress('acme');
        controller.save();
       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='testUserSA@uniquetest.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testUserSA@uniquetest.com');
        	u.IsActive =true;
        	
        	System.runAs(u) {

            RMA__c updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
        	
            updatedRMA.Status__c ='Dispatched';
            update updatedRMA;
            updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
            System.assertEquals('Dispatched', updatedRMA.Status__c);
        }
    }
    
     @IsTest 
    public static void DispatchForNonECProducts()
    {
        Account acc = new Account(Name='acme', Type='Eval');
        insert acc;
        Contact con = new Contact(LastName='acme', AccountId=acc.Id);
        con.MailingStreet='address1 \r\n address2';
        insert con;
        List<Product2> pros = new List<Product2> { 
            new Product2(Name='VX-500', ProductCode='VX-500') };
                insert pros;
        Product2 pro = new Product2(Name='VX-500', ProductCode='VX-500', Model__c='VX-500', RMA_Primary_Replacement__c=pros[0].Id);
        insert pro;
        Asset asset = new Asset(Name='acme', SerialNumber='acme', Quantity=1.00,Status='Conditional PO', Product2Id=pro.Id, AccountId=acc.Id, ContactId=con.Id);
        insert asset;
        NewRMAController controller = new NewRMAController();
        Case caseInfo = new Case(Subject='acme', Status='On Hold', Origin='Email', AssetId=asset.Id, AccountId=acc.Id, ContactId=con.Id);
        caseInfo.Type = controller.getRecordTypeId('System Change Request', 'Case');
        insert caseInfo;
        
        PageReference page = new PageReference('/newrma?id=' + caseInfo.Id);
        Test.setCurrentPageReference(page);
        controller = new NewRMAController();
        controller.getRMA().Type__c = 'Return for Repair'; 
        controller.getRMAItem().Delivery_Class__c = 'Next Business Day';
        List<NewRMAController.ProductInfo> proInfos = new List<NewRMAController.ProductInfo> {
            new NewRMAController.ProductInfo('System'),
                new NewRMAController.ProductInfo('HDD'),
                new NewRMAController.ProductInfo('SSD'),
                new NewRMAController.ProductInfo('Power Supply') };
                    proInfos[0].Selected = true;
        proInfos[1].Selected = false;
        proInfos[2].Selected = false;
        proInfos[3].Selected = false;
        
        controller.Products = proInfos;
        controller.getContact().LastName = 'acme';
        controller.getRMAItem().Contact_Email__c = 'test@test.com';
        controller.getRMAItem().Contact_Phone__c = '123456789';
        controller.getRMAItem().ShipToCountry__c = 'USA';
        controller.getRMAItem().ShipToAddress__c = 'acme';
        controller.getRMAItem().ShipToAddressAdditional__c = 'acme';
        controller.getRMAItem().ShipToCity__c = 'acme';
        controller.getRMAItem().ShipToStateOrProvince__c = 'acme';
        controller.getRMAItem().ShipToPostalCode__c = '100000';
        controller.isEntitledForRMA(asset.Id);
        controller.getDeliveryClasses();
        controller.previous();
        controller.next();
        controller.getRMATypes();
        controller.save();
        controller.cancel();
        controller.createCase();
        NewRMAController.loadContactFromCase(null);
        
        con.Email = 'test@test.com';
        update con;
        PageReference page2 = new PageReference('/newrma?id=' + acc.Id);
        Test.setCurrentPageReference(page2);
        controller.getRMA().Type__c  = 'Advance Replace';
        controller.saveAndNew();
        RMA__c rma = new RMA__c();
        RMA_Item__c rmaItem = new RMA_Item__c();
        controller.setRMA(rma);
        controller.setRMAItem(rmaItem);
        controller.setContact(con);
        NewRMAController.parseAssetAddress('acme');
        controller.save();
       
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
       
             
        User u = new User(Alias = 'standt', Email='testUserSA@uniquetest.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testUserSA@uniquetest.com');
        	u.IsActive =true;
        	
        	System.runAs(u) {
          
                
            
            RMA__c updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
            updatedRMA.Status__c ='Dispatched';
         
            update updatedRMA;
          
            updatedRMA = [Select Id, Status__c from RMA__c where Id= :controller.getRMA().id];
            System.assertEquals('Dispatched', updatedRMA.Status__c);
        }
    }*/
}